// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Bulk delete case file request
 */
export const zEvidenceBulkDeleteEntityRequestModel = z.object({
    requestId: z.uuid(),
    ids: z.array(z.uuid()).min(1).max(100)
});

/**
 * Create case file request
 */
export const zEvidenceCreateCaseFileRequestModel = z.object({
    id: z.uuid(),
    code: z.string().optional(),
    description: z.string().optional(),
    category: z.string().optional(),
    owner: z.string().optional(),
    title: z.string().optional(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

export const zEvidenceUpdateCaseFileRequestModel = z.object({
    code: z.string().optional(),
    description: z.string().optional(),
    category: z.string().optional(),
    owner: z.string().optional(),
    title: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional()
});

export const zEvidenceUpdateEvidenceGroupRequest = z.object({
    name: z.string().max(255).optional(),
    description: z.string().max(255).optional(),
    code: z.string().max(50).optional(),
    createdBy: z.string().max(50).optional(),
    metadata: z.record(z.string(), z.string()).optional()
});

export const zEvidenceCloseEvidenceGroupRequestModel = z.object({
    evidencesCount: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    collectMetadata: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

export const zEvidenceRegisterEvidenceResponseModel = z.object({
    url: z.string().optional(),
    expiration: z.iso.datetime().optional()
});

export const zEvidenceNewUploadUrlRequestModel = z.object({
    fileName: z.string().min(1)
});

/**
 * PreviewReport Request
 */
export const zEvidenceChatPreviewReportRequestModel = z.object({
    template: z.string(),
    languageCode: z.string(),
    fromDate: z.iso.datetime().nullish(),
    toDate: z.iso.datetime().nullish(),
    additionalData: z.record(z.string(), z.unknown()).optional()
});

/**
 * Bulk delete signature request
 */
export const zSignatureBulkDeleteSignatureRequestRequestModel = z.object({
    requestId: z.uuid(),
    signatureRequestIds: z.array(z.uuid()).min(1).max(100)
});

export const zSignatureAddValidatorRequestModel = z.object({
    name: z.string().min(1),
    surnames: z.string().optional(),
    phone: z.string().optional(),
    email: z.email().min(1)
});

/**
 * Validator Response
 */
export const zSignatureValidatorViewModel = z.object({
    id: z.uuid().optional(),
    name: z.string().optional(),
    surnames: z.string().optional(),
    phone: z.string().optional(),
    email: z.string().optional(),
    documentId: z.uuid().optional(),
    signatoryId: z.uuid().optional()
});

export const zSignatureSignatureRequestStatus = z.enum([
    'DRAFT',
    'ACTIVE',
    'PARTIALLY_SIGNED',
    'FULLY_SIGNED',
    'CANCELLED',
    'COMPLETED',
    'COMPLETED_PARTIAL',
    'COMPLETED_EXPIRED',
    'COMPLETED_MANUAL',
    'REJECTED',
    'ERROR',
    'CANCELLED_EXPIRED'
]);

export const zSignatureCancellationReason = z.enum(['REJECTED', 'DEADLINE']);

export const zSignatureDocumentSignatureType = z.enum(['ADVANCED', 'INTERPOSITION']);

export const zSignatureDocumentSignatureProvider = z.enum(['EADTRUST']);

export const zSignatureCloseConditionViewModel = z.enum(['ALL_REQUIRED', 'PARTIAL_ALLOWED']);

/**
 * Activate a Signature Request
 */
export const zSignatureActivateSignatureRequestViewModel = z.object({
    id: z.uuid().optional(),
    status: zSignatureSignatureRequestStatus.optional()
});

/**
 * Cancel a Signature Request
 */
export const zSignatureCancelSignatureRequestViewModel = z.object({
    id: z.uuid().optional(),
    status: zSignatureSignatureRequestStatus.optional()
});

/**
 * Close a Signature Request manually
 */
export const zSignatureCloseSignatureRequestViewModel = z.object({
    id: z.uuid().optional(),
    status: zSignatureSignatureRequestStatus.optional()
});

export const zSignatureDocumentSignatureStatus = z.enum([
    'PENDING',
    'READY_TO_SIGN',
    'REVIEWED',
    'PARTIALLY_SIGNED',
    'SIGNED',
    'REJECTED',
    'ERROR',
    'CONVERTING_PDF'
]);

/**
 * Document Response
 */
export const zSignatureAddDocumentViewModel = z.object({
    id: z.uuid().optional(),
    url: z.string().optional(),
    expiration: z.iso.datetime().optional()
});

export const zSignatureDocumentMultipartViewModel = z.object({
    id: z.uuid().optional(),
    uploadId: z.string().optional(),
    status: z.string().optional()
});

export const zSignatureFileDocumentSignedDownloadUrlViewModel = z.object({
    url: z.string().optional(),
    expiration: z.iso.datetime().optional()
});

/**
 * Get a document upload URL
 */
export const zSignatureGetUploadUrlViewModel = z.object({
    url: z.string().optional(),
    expiration: z.iso.datetime().optional()
});

export const zSignatureAddObserverRequestModel = z.object({
    name: z.string().min(1),
    surnames: z.string().optional(),
    email: z.email().min(1)
});

export const zSignatureUpdateObserverRequestModel = z.object({
    name: z.string().optional(),
    surnames: z.string().optional(),
    email: z.email().optional()
});

export const zSignatureUpdateDocumentSequenceRequestModel = z.object({
    sequence: z.int().optional()
});

export const zSignatureUpdateSignatoryRequestModel = z.object({
    name: z.string().optional(),
    surnames: z.string().optional(),
    phone: z.string().optional(),
    uniqueValidator: z.boolean().optional(),
    email: z.email().optional(),
    sequence: z.int().optional()
});

export const zSignatureUpdateSignatorySequenceRequestModel = z.object({
    sequence: z.int().optional()
});

export const zSignatureUpdateValidatorRequestModel = z.object({
    name: z.string().optional(),
    surnames: z.string().optional(),
    phone: z.string().optional(),
    email: z.email().optional()
});

export const zSignatureUploadLinkOutputModel = z.object({
    url: z.string().optional(),
    expiration: z.iso.datetime().optional()
});

/**
 * Draft a Signature Request
 */
export const zSignatureDraftSignatureRequestViewModel = zSignatureActivateSignatureRequestViewModel;

/**
 * Create interim report
 */
export const zSignatureSignatureRequestReportRequestModel = z.object({
    reportId: z.uuid().optional(),
    documentId: z.uuid(),
    additionalData: z.record(z.string(), z.unknown()).and(z.unknown()).optional()
});

/**
 * Signature Report Response
 */
export const zSignatureSignatureRequestReportViewModel = z.object({
    signatureRequestId: z.uuid().optional(),
    reportId: z.uuid().optional(),
    documentId: z.uuid().optional()
});

/**
 * Bulk delete notification request
 */
export const zNotificationBulkDeleteEntityRequestModel = z.object({
    requestId: z.uuid(),
    ids: z.array(z.uuid()).min(1).max(100)
});

export const zNotificationNotificationStateType1 = z.enum([
    'DRAFT',
    'ACTIVE',
    'DISPATCHED',
    'DISPATCH_FAILED',
    'DELIVERING',
    'ERROR',
    'SENT',
    'OPEN',
    'READ',
    'ACCEPTED',
    'NOT_ACCEPTED',
    'RECEIVED_CONFORMING',
    'RECEIVED_NON_CONFORMING',
    'ANSWERED',
    'CANCELLED',
    'BOUNCED',
    'RELAYED'
]);

export const zNotificationReceiversNotificationViewModel = z.object({
    requestId: z.uuid().optional(),
    notificationIds: z.array(z.uuid()).optional()
});

export const zNotificationDeleteRequestReceiver = z.object({
    notificationIds: z.array(z.uuid()).min(1)
});

export const zNotificationUpdateOnLiveNotificationRequestModel = z.object({
    name: z.string().min(1),
    address: z.email().min(1),
    phone: z.string().optional()
});

export const zNotificationUpdateOnLiveNotificationViewModel = z.object({
    oldNotificationId: z.uuid().optional(),
    newNotificationId: z.uuid().optional()
});

export const zNotificationCloneNotificationRequestModel = z.object({
    requestId: z.uuid().optional(),
    recipientEmail: z.email().optional(),
    subject: z.string().optional(),
    senderName: z.string().optional(),
    senderAddress: z.email().optional()
});

export const zNotificationCloneNotificationViewModel = z.object({
    oldNotificationId: z.uuid().optional(),
    newNotificationId: z.uuid().optional()
});

export const zNotificationResendNotificationViewModel = z.object({
    oldNotificationId: z.uuid().optional(),
    newNotificationId: z.uuid().optional()
});

/**
 * Report Request
 */
export const zNotificationGenerateNotificationReportRequestModel = z.object({
    reportId: z.uuid().optional(),
    requestId: z.uuid(),
    template: z.string().min(1),
    languageCode: z.string().min(1),
    notificationIds: z.array(z.uuid()),
    additionalData: z.record(z.string(), z.string()).and(z.unknown()).optional(),
    embedAttachmentsEnabled: z.boolean().optional()
});

/**
 * Notification report response
 */
export const zNotificationNotificationReportViewModel = z.object({
    reportId: z.uuid().optional(),
    requestId: z.uuid().optional(),
    template: z.string(),
    languageCode: z.string(),
    notificationIds: z.array(z.uuid()),
    additionalData: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

export const zNotificationUploadNotificationAttachmentModel = z.object({
    fileSize: z.int().gte(1).optional()
});

export const zNotificationUploadNotificationAttachmentUrlViewModel = z.object({
    url: z.string().optional(),
    expiration: z.iso.datetime().optional()
});

/**
 * Add this field to filter by the status of a case file
 */
export const zEvidenceCaseFileStatus3 = z.enum(['OPEN', 'CLOSE']);

/**
 * Search case file request
 */
export const zEvidenceSearchCaseFileRequestModel = z.object({
    id: z.array(z.uuid()).nullish(),
    code: z.string().nullish(),
    title: z.string().nullish(),
    category: z.array(z.string()).nullish(),
    owner: z.array(z.string()).nullish(),
    status: zEvidenceCaseFileStatus3.nullish(),
    createdFrom: z.iso.datetime().nullish(),
    createdUntil: z.iso.datetime().nullish(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).nullish(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    sort: z.enum(['code, title, category, owner, status, createdAt']).optional()
});

/**
 * Current status of the case file
 */
export const zEvidenceCaseFileStatus = z.enum(['OPEN', 'CLOSE']);

/**
 * Get case file response
 */
export const zEvidenceGetCaseFileViewModel = z.object({
    id: z.uuid().optional(),
    code: z.string().optional(),
    description: z.string().optional(),
    category: z.string().optional(),
    owner: z.string().optional(),
    status: zEvidenceCaseFileStatus.and(z.string()).optional(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional(),
    groups: z.string().optional(),
    title: z.string().optional(),
    createdAt: z.iso.datetime().optional(),
    updatedAt: z.iso.datetime().optional()
});

/**
 * Type of the group
 */
export const zEvidenceGroupType = z.enum([
    'FILE',
    'PHOTO',
    'VIDEO',
    'WEB_PLUGIN'
]);

export const zEvidenceCreateEvidenceGroupRequestModel = z.object({
    id: z.uuid(),
    code: z.string().max(50).optional(),
    type: zEvidenceGroupType,
    name: z.string().max(255).optional(),
    description: z.string().max(255).optional(),
    createdBy: z.string().max(50).optional(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

/**
 * Status of the group
 */
export const zEvidenceEvidenceGroupStatus = z.enum([
    'OPEN',
    'CLOSING',
    'CLOSED'
]);

export const zEvidenceEvidenceGroupSearch = z.object({
    caseFileId: z.uuid().nullish(),
    id: z.array(z.uuid()).nullish(),
    code: z.string().nullish(),
    name: z.string().nullish(),
    status: zEvidenceEvidenceGroupStatus.nullish(),
    type: zEvidenceGroupType.nullish(),
    createdBy: z.string().nullish(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).nullish(),
    createdFrom: z.iso.datetime().nullish(),
    createdUntil: z.iso.datetime().nullish(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    sort: z.enum(['name, createdAt']).optional()
});

/**
 * Count of the evidences that belong to the group
 */
export const zEvidenceEvidencesCountViewModel = z.object({
    total: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    inProcess: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    failed: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    completed: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

/**
 * Evidence Group response
 */
export const zEvidenceEvidenceGroupViewModel = z.object({
    id: z.uuid().optional(),
    caseFileId: z.uuid().optional(),
    collectionMetadataId: z.uuid().optional(),
    code: z.string().optional(),
    name: z.string().optional(),
    type: z.string().optional(),
    status: zEvidenceEvidenceGroupStatus.optional(),
    description: z.string().optional(),
    createdAt: z.iso.datetime().optional(),
    createdBy: z.string().optional(),
    evidences: zEvidenceEvidencesCountViewModel.optional(),
    discarded: z.boolean().optional(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

/**
 * Field that indicates if the evidence is hosted by the system or not
 */
export const zEvidenceCustodyType = z.enum(['INTERNAL', 'EXTERNAL']);

export const zEvidenceTestimonyProviders = z.object({
    required: z.boolean().optional(),
    providers: z.array(z.string()).optional()
});

/**
 * Deletion type: FILE_ONLY (delete file, keep evidence record) or FULL (delete file and mark evidence deleted). Required when deletionDate is provided.
 */
export const zEvidenceEvidenceDeletionType = z.enum(['FILE_ONLY', 'FULL']);

export const zEvidenceRegisterEvidenceRequestModel = z.object({
    evidenceId: z.uuid(),
    hash: z.string().min(1).regex(/^([a-f0-9]{64})$/),
    createdBy: z.string().max(50).optional(),
    title: z.string().optional(),
    type: z.string().optional(),
    capturedAt: z.iso.datetime(),
    custodyType: zEvidenceCustodyType,
    fileName: z.string().optional(),
    fileSize: z.int().optional(),
    testimony: z.object({
        TSP: zEvidenceTestimonyProviders.optional(),
        DLT: zEvidenceTestimonyProviders.optional()
    }).and(z.unknown()),
    requiredTestimonyProviders: z.array(z.string()),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional(),
    deletionDate: z.iso.datetime().nullish(),
    deletionType: zEvidenceEvidenceDeletionType.nullish()
});

/**
 * Status of the evidence, with extra information about the timestamping processes of the evidence
 */
export const zEvidenceGetEvidenceStatusViewModel = z.object({
    status: z.string().optional(),
    tspTimestamp: z.record(z.string(), z.string()).and(z.unknown()).optional(),
    dltTimestamp: z.record(z.string(), z.string()).and(z.unknown()).optional(),
    file: z.string().optional()
});

/**
 * Object type of the download
 */
export const zEvidenceObjectType1 = z.enum([
    'EVIDENCE',
    'REPORT',
    'REPORT_PACKAGE',
    'TEMPLATE'
]);

export const zEvidenceDownloadUrlModel1 = z.object({
    id: z.uuid().optional(),
    type: zEvidenceObjectType1.optional(),
    url: z.string().optional(),
    expiration: z.iso.datetime().optional()
});

/**
 * Field that indicates what type of relationship is assigned
 */
export const zEvidenceRelationshipItemType = z.enum(['CHAT_CONVERSATION']);

export const zEvidenceAssignRelationshipRequestModel = z.object({
    itemType: zEvidenceRelationshipItemType,
    itemValue: z.string()
});

/**
 * Date from which the evidence will be scheduled for deletion. Set to null to cancel scheduled deletion.
 */
export const zEvidencePatchFieldZonedDateTime = z.object({
    value: z.iso.datetime().optional(),
    provided: z.boolean().optional()
});

/**
 * Request to update a case file report
 */
export const zEvidenceUpdateCaseFileReportRequestModel = z.object({
    deletionDate: zEvidencePatchFieldZonedDateTime.nullish()
});

export const zEvidenceObjectType = z.enum([
    'EVIDENCE',
    'THUMBNAIL',
    'REPORT',
    'REPORT_PACKAGE',
    'TEMPLATE',
    'TEMPORARY_FILE',
    'FONT',
    'NOTIFICATION_ATTACHMENT',
    'SIGN_FILE_ORIGINAL',
    'SIGN_FILE_SIGNED',
    'SCRIBBLE',
    'CONVERTED',
    'NOTICEMAN_EVIDENCE'
]);

export const zEvidenceDownloadUrlModel = z.object({
    id: z.uuid().optional(),
    type: zEvidenceObjectType.optional(),
    url: z.string().optional(),
    expiration: z.iso.datetime().optional()
});

/**
 * New status of the case file
 */
export const zEvidenceCaseFileStatusViewModel = z.enum(['OPEN', 'CLOSE']);

export const zEvidenceUpdateCaseFileStatusRequestModel = z.object({
    status: zEvidenceCaseFileStatusViewModel.and(z.string())
});

/**
 * SearchEvidenceGroup response
 */
export const zEvidenceSearchEvidenceGroupViewModel = z.object({
    id: z.uuid().optional(),
    groupId: z.uuid().optional(),
    caseFileId: z.uuid().optional(),
    collectionMetadataId: z.uuid().optional(),
    code: z.string().optional(),
    name: z.string().optional(),
    type: zEvidenceGroupType.optional(),
    status: zEvidenceEvidenceGroupStatus.optional(),
    createdBy: z.string().optional(),
    discarded: z.boolean().optional(),
    createdAt: z.iso.datetime().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    evidences: zEvidenceEvidencesCountViewModel.optional()
});

export const zEvidenceTestimonyMode = z.enum(['TSP', 'DLT']);

export const zEvidenceEvidenceStatus = z.enum([
    'ERROR',
    'IN_PROCESS',
    'COMPLETED'
]);

export const zEvidenceSearchEvidenceRequestModel = z.object({
    id: z.array(z.uuid()).nullish(),
    caseFileId: z.uuid().nullish(),
    groupId: z.array(z.uuid()).nullish(),
    groupType: z.array(zEvidenceGroupType).nullish(),
    title: z.string().nullish(),
    type: z.string().optional(),
    hash: z.string().nullish(),
    custodyType: zEvidenceCustodyType.nullish(),
    testimonyMode: z.array(zEvidenceTestimonyMode).nullish(),
    status: z.array(zEvidenceEvidenceStatus).nullish(),
    fileName: z.string().nullish(),
    fileSize: z.int().nullish(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).nullish(),
    capturedFrom: z.iso.datetime().nullish(),
    capturedUntil: z.iso.datetime().nullish(),
    collectionMetadata: z.boolean().nullish(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    sort: z.enum(['capturedAt, groupName']).optional()
});

/**
 * Deletion type: FILE_ONLY or FULL. Required when deletionDate is provided with a non-null value.
 */
export const zEvidencePatchFieldEvidenceDeletionType = z.object({
    value: zEvidenceEvidenceDeletionType.optional(),
    provided: z.boolean().optional()
});

export const zEvidenceUpdateEvidenceRequestModel = z.object({
    title: z.string().optional(),
    createdBy: z.string().max(50).optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    custody: zEvidenceCustodyType.optional(),
    deletionDate: zEvidencePatchFieldZonedDateTime.nullish(),
    deletionType: zEvidencePatchFieldEvidenceDeletionType.nullish()
});

export const zEvidenceTestimonyDataQueryModel = z.object({
    required: z.boolean().optional(),
    providers: z.array(z.string()).optional()
});

export const zEvidenceUploadUrlTemporaryFileHttpRequestModel = z.object({
    caseFileId: z.uuid().optional(),
    evidenceGroupId: z.uuid().optional(),
    evidenceId: z.uuid(),
    createdBy: z.string(),
    title: z.string(),
    capturedAt: z.iso.datetime(),
    fileName: z.string(),
    testimony: z.record(z.string(), zEvidenceTestimonyDataQueryModel),
    requiredTestimonyProviders: z.array(z.string()).optional(),
    metadata: z.record(z.string(), z.string()).optional()
});

export const zEvidenceStartMultipartUploadRequestModel = z.object({
    caseFileId: z.uuid().optional(),
    evidenceGroupId: z.uuid().optional(),
    createdBy: z.string(),
    title: z.string().min(1),
    capturedAt: z.iso.datetime(),
    testimony: z.record(z.string(), zEvidenceTestimonyDataQueryModel),
    requiredTestimonyProviders: z.array(z.string()).optional(),
    metadata: z.record(z.string(), z.string()).optional()
});

export const zSignatureAbstractCollectionDownloadUrlViewModel = z.object({
    empty: z.boolean().optional()
});

export const zSignatureHashSetDownloadUrlViewModel = zSignatureAbstractCollectionDownloadUrlViewModel.and(z.object({
    empty: z.boolean().optional()
}));

/**
 * Get a document download URL
 */
export const zSignatureFileDocumentDownloadUrlViewModel = zSignatureHashSetDownloadUrlViewModel.and(zSignatureAbstractCollectionDownloadUrlViewModel).and(z.object({
    empty: z.boolean().optional()
}));

export const zSignatureAbstractSetDownloadUrlViewModel = zSignatureAbstractCollectionDownloadUrlViewModel;

/**
 * Close config response
 */
export const zSignatureCloseConfigViewModel = z.object({
    condition: zSignatureCloseConditionViewModel.optional(),
    date: z.iso.datetime().optional()
});

export const zSignatureWebhookUriViewModel = z.object({
    uri: z.url().regex(/^https:\/\//).optional()
});

/**
 * Signature request response
 */
export const zSignatureSignatureRequestViewModel1 = z.object({
    id: z.uuid().optional(),
    status: zSignatureSignatureRequestStatus.optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    cancellationReason: zSignatureCancellationReason.optional(),
    createdBy: z.string().optional(),
    senderName: z.string().optional(),
    createdAt: z.iso.datetime().optional(),
    uniqueValidator: z.boolean().optional(),
    closeConfig: zSignatureCloseConfigViewModel.optional(),
    webhookUris: z.array(zSignatureWebhookUriViewModel).optional()
});

export const zSignatureSignatureRequestProvider = z.enum([
    'NOTICEMAN',
    'NOTICEMAN_AND_WHATSAPP',
    'NOTICEMAN_AND_WHATSAPP_AND_RCS',
    'NOTICEMAN_AND_RCS'
]);

export const zSignatureWebhookUri = z.object({
    uri: z.url().regex(/^https:\/\//).optional()
});

export const zSignatureSigningConfigurationSigningProvider = z.enum(['EADTRUST']);

export const zSignatureSigningObjectConfigurationSigningTypes = z.enum([
    'INTERPOSITION',
    'ADVANCED',
    'OTHER'
]);

export const zSignatureCertificateFilesRequestModel = z.object({
    originalDocument: z.boolean().optional(),
    signedDocument: z.boolean().optional()
});

/**
 * Add document request model
 */
export const zSignatureAddDocumentRequestModel = z.object({
    filename: z.string().min(1),
    title: z.string().min(1),
    description: z.string().optional(),
    hash: z.string().min(1).regex(/^([a-f0-9]{64})$/),
    signatureDeadline: z.iso.datetime().optional(),
    provider: zSignatureSigningConfigurationSigningProvider.optional(),
    signatureType: zSignatureSigningObjectConfigurationSigningTypes,
    evidenceId: z.uuid().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    certificateFiles: zSignatureCertificateFilesRequestModel.optional(),
    sequence: z.int().optional(),
    fileSize: z.int().gte(1).optional(),
    detached: z.boolean().optional(),
    convertToPdf: z.boolean().optional()
});

/**
 * Participant Notification Response
 */
export const zSignatureParticipantNotificationViewModel = z.object({
    id: z.string().optional(),
    status: z.string().optional(),
    createdAt: z.iso.datetime().optional()
});

/**
 * Observer Response
 */
export const zSignatureObserverViewModel = z.object({
    id: z.uuid().optional(),
    name: z.string().optional(),
    surnames: z.string().optional(),
    email: z.string().optional(),
    notifications: z.array(zSignatureParticipantNotificationViewModel).optional()
});

export const zSignatureSignatoryCoordinatesViewModel = z.object({
    x: z.number().optional(),
    y: z.number().optional(),
    page: z.int().optional()
});

export const zSignatureSignatoryParticipantType = z.enum(['HUMAN', 'LEGAL_ENTITY']);

export const zSignatureAddSignatoryCoordinatesRequestModel = z.object({
    x: z.number(),
    y: z.number(),
    page: z.int()
});

export const zSignatureAddSignatoryRequestModel = z.object({
    name: z.string().min(1),
    surnames: z.string().optional(),
    email: z.email().min(1),
    phone: z.string().optional(),
    coordinates: z.array(zSignatureAddSignatoryCoordinatesRequestModel).optional(),
    sequence: z.int().optional(),
    uniqueValidator: z.boolean().optional()
});

export const zSignatureSignatoryCoordinatesRequestModel = z.object({
    x: z.number().optional(),
    y: z.number().optional(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zSignatureUpdateSignatoryCoordinatesRequestModel = z.object({
    coordinates: z.array(zSignatureSignatoryCoordinatesRequestModel).optional()
});

export const zNotificationNotificationSearchCommonFilters = z.object({
    recipients: z.array(z.string()).nullish()
});

export const zNotificationRequestAttachmentRequestModel = z.object({
    fileName: z.string().min(1),
    hash: z.string().min(1).regex(/^([a-f0-9]{64})$/),
    fileId: z.uuid().optional(),
    fileSize: z.int().gte(1).optional()
});

export const zNotificationAddRequestAttachmentRequestModel = z.object({
    attachments: z.array(zNotificationRequestAttachmentRequestModel).min(1)
});

export const zNotificationUploadRequestAttachmentLinkModel = z.object({
    url: z.string().optional(),
    expiration: z.iso.datetime().optional(),
    fileId: z.uuid().optional()
});

/**
 * Add Request Attachment Response
 */
export const zNotificationAddRequestAttachmentViewModel = z.object({
    requestId: z.uuid().optional(),
    notificationIds: z.array(z.uuid()).optional(),
    uploadLinks: z.array(zNotificationUploadRequestAttachmentLinkModel).optional()
});

export const zNotificationUploadAttachmentLinkModel = z.object({
    url: z.string().optional(),
    expiration: z.iso.datetime().optional(),
    filename: z.string().optional(),
    fileId: z.uuid().optional()
});

export const zNotificationRegisterNotificationViewModel = z.object({
    requestId: z.uuid().optional(),
    notificationIds: z.array(z.uuid()).optional(),
    uploadLinks: z.array(zNotificationUploadAttachmentLinkModel).optional()
});

export const zNotificationNotificationTypeViewModel = z.enum([
    'NO_RESPONSE',
    'ACCEPTED_OR_NOT',
    'RECEIVED_AGREE',
    'LONG_RESPONSE'
]);

export const zNotificationAbstractCollectionDownloadUrlViewModel = z.object({
    empty: z.boolean().optional()
});

export const zNotificationHashSetDownloadUrlViewModel = zNotificationAbstractCollectionDownloadUrlViewModel.and(z.object({
    empty: z.boolean().optional()
}));

/**
 * Get a document download URL
 */
export const zNotificationFileDocumentDownloadUrlViewModel = zNotificationHashSetDownloadUrlViewModel.and(zNotificationAbstractCollectionDownloadUrlViewModel).and(z.object({
    empty: z.boolean().optional()
}));

/**
 * Get a document download URL
 */
export const zNotificationNotificationAttachmentDownloadUrlViewModel = zNotificationHashSetDownloadUrlViewModel.and(zNotificationAbstractCollectionDownloadUrlViewModel).and(z.object({
    empty: z.boolean().optional()
}));

export const zNotificationAbstractSetDownloadUrlViewModel = zNotificationAbstractCollectionDownloadUrlViewModel;

export const zEvidenceMetadata = z.object({
    currentPage: z.int().optional(),
    totalPages: z.int().optional(),
    pageSize: z.int().optional(),
    totalRecords: z.int().optional()
});

export const zEvidenceBaseCollectionViewModelSearchEvidenceGroupViewModel = z.object({
    records: z.array(zEvidenceSearchEvidenceGroupViewModel).optional(),
    _metadata: zEvidenceMetadata.optional()
});

export const zEvidenceSearchEvidenceGroupCollectionViewModel = zEvidenceBaseCollectionViewModelSearchEvidenceGroupViewModel.and(z.object({
    records: z.array(zEvidenceSearchEvidenceGroupViewModel).optional()
}));

/**
 * Current status of the case file
 */
export const zEvidenceCaseFileStatus1 = z.enum(['OPEN', 'CLOSE']);

/**
 * Search case file response
 */
export const zEvidenceSearchCaseFileViewModel = z.object({
    id: z.uuid().optional(),
    title: z.string().optional(),
    code: z.string().optional(),
    category: z.string().optional(),
    owner: z.string().optional(),
    status: zEvidenceCaseFileStatus1.and(z.string()).optional(),
    createdAt: z.iso.datetime().optional(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

export const zEvidenceBaseCollectionViewModelSearchCaseFileViewModel = z.object({
    records: z.array(zEvidenceSearchCaseFileViewModel).optional(),
    _metadata: zEvidenceMetadata.optional()
});

export const zEvidenceSearchCaseFileCollectionViewModel = zEvidenceBaseCollectionViewModelSearchCaseFileViewModel.and(z.object({
    records: z.array(zEvidenceSearchCaseFileViewModel).optional()
}));

export const zEvidenceTspTimestampViewModel = z.object({
    token: z.string().optional(),
    timestampedAt: z.iso.datetime().optional()
});

export const zEvidenceDltTimestampViewModel = z.object({
    blockHash: z.string().optional(),
    transactionHash: z.string().optional(),
    network: z.string().optional(),
    blockExplorerLink: z.string().optional(),
    timestampedAt: z.iso.datetime().optional()
});

/**
 * Information about the timestamps of the evidence: DLT information + TSP information
 */
export const zEvidenceGetEvidenceTimestampsViewModel = z.object({
    tspTimestamps: z.record(z.string(), zEvidenceTspTimestampViewModel).optional(),
    dltTimestamps: z.record(z.string(), zEvidenceDltTimestampViewModel).optional()
});

export const zEvidenceGetEvidenceViewModel = z.object({
    caseFileId: z.uuid().optional(),
    groupId: z.uuid().optional(),
    evidenceId: z.uuid().optional(),
    title: z.string().optional(),
    custodyType: z.string().optional(),
    status: zEvidenceGetEvidenceStatusViewModel.optional(),
    capturedAt: z.iso.datetime().optional(),
    fileName: z.string().optional(),
    fileSize: z.int().optional(),
    hash: z.string().optional(),
    timestamps: zEvidenceGetEvidenceTimestampsViewModel.optional(),
    createdBy: z.string().optional(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

/**
 * Information about the group of the evidence
 */
export const zEvidenceSearchEvidenceGroupInfoViewModel = z.object({
    id: z.uuid().optional(),
    name: z.string().optional(),
    type: zEvidenceGroupType.optional(),
    code: z.string().optional()
});

/**
 * Search evidence response
 */
export const zEvidenceSearchEvidenceViewModel = z.object({
    id: z.uuid().optional(),
    caseFileId: z.uuid().optional(),
    group: zEvidenceSearchEvidenceGroupInfoViewModel.optional(),
    title: z.string().optional(),
    type: z.string().optional(),
    hash: z.string().optional(),
    fileSize: z.int().optional(),
    custodyType: z.string().optional(),
    createdBy: z.string().optional(),
    capturedAt: z.iso.datetime().optional(),
    fileName: z.string().optional(),
    status: zEvidenceGetEvidenceStatusViewModel.optional(),
    timestamps: zEvidenceGetEvidenceTimestampsViewModel.optional(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

export const zEvidenceBaseCollectionViewModelSearchEvidenceViewModel = z.object({
    records: z.array(zEvidenceSearchEvidenceViewModel).optional(),
    _metadata: zEvidenceMetadata.optional()
});

export const zEvidenceSearchEvidenceCollectionViewModel = zEvidenceBaseCollectionViewModelSearchEvidenceViewModel.and(z.object({
    records: z.array(zEvidenceSearchEvidenceViewModel).optional()
}));

/**
 * Create Signature Request request
 */
export const zSignatureSignatureRequestStatusTypeModel = z.enum([
    'DRAFT',
    'ACTIVE',
    'REJECTED',
    'COMPLETED',
    'CANCELLED'
]);

/**
 * Create Signature Request request
 */
export const zSignatureCloseCondition = z.enum(['ALL_REQUIRED', 'PARTIAL_ALLOWED']);

export const zSignatureCloseConfig = z.object({
    condition: zSignatureCloseCondition.optional(),
    date: z.iso.datetime().optional()
});

/**
 * Close configuration for updating a Signature Request
 */
export const zSignatureUpdateCloseConfigModel = z.object({
    date: z.iso.datetime().optional(),
    condition: zSignatureCloseCondition.optional()
});

export const zSignatureBaseEntity = z.object({
    createdAt: z.iso.datetime().optional(),
    updatedAt: z.iso.datetime().optional()
});

export const zSignatureSignatureRequestStatusType = z.enum([
    'DRAFT',
    'ACTIVE',
    'PARTIALLY_SIGNED',
    'FULLY_SIGNED',
    'CANCELLED',
    'COMPLETED',
    'COMPLETED_PARTIAL',
    'COMPLETED_EXPIRED',
    'COMPLETED_MANUAL',
    'REJECTED',
    'ERROR',
    'CANCELLED_EXPIRED'
]);

export const zSignatureSignatureRequestStatusViewModel = z.object({
    signatureRequestId: z.uuid().optional(),
    registeredAt: z.iso.datetime().optional(),
    status: zSignatureSignatureRequestStatusType.optional()
});

export const zSignatureParticipantRole = z.enum([
    'SIGNATORY',
    'OBSERVER',
    'VALIDATOR'
]);

export const zSignatureSignatureRequestBody = zSignatureBaseEntity.and(z.object({
    signatureRequestId: z.uuid().optional(),
    status: zSignatureSignatureRequestStatusType.optional(),
    participantRole: zSignatureParticipantRole.optional(),
    body: z.string().optional(),
    subject: z.string().optional(),
    additionalText: z.string().optional()
}));

/**
 * Signature Response
 */
export const zSignatureSignatureRequestViewModel = z.object({
    id: z.uuid().optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    createdBy: z.string().optional(),
    senderName: z.string().optional(),
    senderAddress: z.string().optional(),
    signatureRequestBody: z.array(zSignatureSignatureRequestBody).optional(),
    cancellationReason: zSignatureCancellationReason.optional(),
    status: zSignatureSignatureRequestStatus.optional(),
    notifications: z.boolean().optional(),
    language: z.string().optional(),
    uniqueValidator: z.boolean().optional(),
    provider: zSignatureSignatureRequestProvider.optional(),
    webhookUris: z.array(zSignatureWebhookUriViewModel).optional()
});

export const zSignatureCoordinatesViewModel = z.object({
    x: z.number().optional(),
    y: z.number().optional(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zSignatureLegalEntitySignerViewModel = z.object({
    id: z.uuid().optional(),
    signatureRequestId: z.uuid().optional(),
    documentId: z.uuid().optional(),
    name: z.string().optional(),
    taxId: z.string().optional(),
    roleType: z.string().optional(),
    status: z.string().optional(),
    signedAt: z.iso.datetime().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    coordinates: z.array(zSignatureCoordinatesViewModel).optional()
});

export const zSignatureGetEvidenceStatusViewModel = z.object({
    status: z.string().optional(),
    tspTimestamp: z.record(z.string(), z.string()).optional(),
    dltTimestamp: z.record(z.string(), z.string()).optional(),
    file: z.string().optional()
});

export const zSignatureSignatureValidatorStatus = z.enum([
    'PENDING',
    'READY_TO_VALIDATE',
    'VALIDATED',
    'REJECTED',
    'ERROR'
]);

export const zSignatureSignatoryValidatorViewModel = z.object({
    id: z.uuid().optional(),
    name: z.string().optional(),
    surnames: z.string().optional(),
    email: z.string().optional(),
    status: zSignatureSignatureValidatorStatus.optional(),
    notifications: z.array(zSignatureParticipantNotificationViewModel).optional()
});

/**
 * Signatory Response
 */
export const zSignatureSignatoryViewModel = z.object({
    id: z.uuid().optional(),
    name: z.string().optional(),
    surnames: z.string().optional(),
    email: z.string().optional(),
    documentId: z.uuid().optional(),
    phone: z.string().optional(),
    signatureStatus: zSignatureDocumentSignatureStatus.optional(),
    coordinates: z.array(zSignatureSignatoryCoordinatesViewModel).optional(),
    registeredAt: z.iso.datetime().optional(),
    signatures: z.array(z.lazy((): any => zSignatureSignatoryViewModel)).optional(),
    sequence: z.int().optional(),
    uniqueValidator: z.boolean().optional(),
    validators: z.array(zSignatureSignatoryValidatorViewModel).optional(),
    notifications: z.array(zSignatureParticipantNotificationViewModel).optional(),
    participantType: zSignatureSignatoryParticipantType.optional(),
    taxId: z.string().optional(),
    roleType: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional()
});

export const zSignatureGetDocumentsViewModel = z.object({
    id: z.uuid().optional(),
    filename: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    signatureDeadline: z.iso.datetime().optional(),
    provider: zSignatureDocumentSignatureProvider.optional(),
    signatureType: zSignatureDocumentSignatureType.optional(),
    status: zSignatureDocumentSignatureStatus.optional(),
    signatories: z.array(zSignatureSignatoryViewModel).optional(),
    observers: z.array(zSignatureObserverViewModel).optional(),
    fileSize: z.int().optional(),
    sequence: z.int().optional(),
    legalEntitySigners: z.array(zSignatureLegalEntitySignerViewModel).optional()
});

export const zSignatureMetadata = z.object({
    currentPage: z.int().optional(),
    totalPages: z.int().optional(),
    pageSize: z.int().optional(),
    totalRecords: z.int().optional()
});

export const zSignatureBaseCollectionViewModelValidatorViewModel = z.object({
    records: z.array(zSignatureValidatorViewModel).optional(),
    _metadata: zSignatureMetadata.optional()
});

export const zSignatureListValidatorsViewModel = zSignatureBaseCollectionViewModelValidatorViewModel.and(z.object({
    records: z.array(zSignatureValidatorViewModel).optional()
}));

export const zNotificationMetadata = z.object({
    currentPage: z.int().optional(),
    totalPages: z.int().optional(),
    pageSize: z.int().optional(),
    totalRecords: z.int().optional()
});

export const zNotificationNotificationType1 = z.enum([
    'NO_RESPONSE',
    'ACCEPTED_OR_NOT',
    'RECEIVED_AGREE',
    'LONG_RESPONSE'
]);

/**
 * Receiver Email
 */
export const zNotificationAddReceiverEmailNotificationRequestModel = z.object({
    provider: z.enum(['SMTP']),
    address: z.email().min(1),
    name: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional()
});

/**
 * Receiver SMS
 */
export const zNotificationAddReceiverSmsNotificationRequestModel = z.object({
    provider: z.enum(['SMS']),
    address: z.string().min(1)
});

/**
 * Receiver WFB
 */
export const zNotificationAddReceiverWfbNotificationRequestModel = z.object({
    provider: z.enum(['WFB']),
    address: z.string().min(1)
});

export const zNotificationRegisterNotificationSmsRequestModel = z.object({
    receiverAddresses: z.array(z.string()).min(1)
});

export const zNotificationRegisterNotificationWhatsappRequestModel = z.object({
    receiverAddresses: z.array(z.string()).min(1)
});

export const zNotificationNotificationStateTypeViewModel = z.enum([
    'DRAFT',
    'ACTIVE',
    'DISPATCHED',
    'DISPATCH_FAILED',
    'DELIVERING',
    'ERROR',
    'SENT',
    'OPEN',
    'READ',
    'ACCEPTED',
    'NOT_ACCEPTED',
    'RECEIVED_CONFORMING',
    'RECEIVED_NON_CONFORMING',
    'ANSWERED',
    'CANCELLED',
    'BOUNCED',
    'RELAYED'
]);

/**
 * Notification detail response
 */
export const zNotificationNotificationStateViewModel = z.object({
    registeredAt: z.iso.datetime().optional(),
    type: zNotificationNotificationStateTypeViewModel.optional()
});

export const zNotificationFileTypeViewModel = z.enum([
    'EVIDENCE',
    'THUMBNAIL',
    'REPORT',
    'REPORT_PACKAGE',
    'TEMPLATE',
    'TEMPORARY_FILE',
    'FONT',
    'NOTIFICATION_ATTACHMENT'
]);

export const zNotificationNotificationAttachmentStatusViewModel = z.enum([
    'WAITING_FILE',
    'READY_TO_SEND',
    'REVIEWED'
]);

export const zNotificationNotificationAttachmentViewModel = z.object({
    fileId: z.uuid().optional(),
    filename: z.string().optional(),
    hash: z.string().optional(),
    fileType: zNotificationFileTypeViewModel.optional(),
    attachmentStatus: zNotificationNotificationAttachmentStatusViewModel.optional(),
    fileSize: z.int().optional(),
    reviewedAt: z.iso.datetime().optional()
});

/**
 * Notification detail response
 */
export const zNotificationNotificationDetailViewModel = z.object({
    id: z.uuid().optional(),
    externalId: z.string().optional(),
    senderAddress: z.string().optional(),
    senderName: z.string().optional(),
    senderAddressReplyTo: z.string().optional(),
    recipientAddress: z.string().optional(),
    recipientName: z.string().optional(),
    subject: z.string().optional(),
    content: z.string().optional(),
    states: z.array(zNotificationNotificationStateViewModel).optional(),
    type: zNotificationNotificationTypeViewModel.optional(),
    phone: z.string().optional(),
    reminderHours: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    scheduledAt: z.iso.datetime().optional(),
    limitResponse: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    notificationAttachments: z.array(zNotificationNotificationAttachmentViewModel).optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    provider: z.string().optional(),
    rcsType: z.string().optional(),
    templateId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    templateAttributes: z.record(z.string(), z.string()).optional(),
    priority: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    auxiliarySmsText: z.string().optional()
});

export const zEvidenceBulkPatchOperation = z.enum(['REPLACE', 'REMOVE']);

export const zEvidenceBulkPatchOperationRequestModel = z.object({
    operation: zEvidenceBulkPatchOperation,
    path: z.string(),
    value: z.string().optional()
});

export const zEvidenceBulkPatchRequestModel = z.object({
    ids: z.array(z.string()).min(1),
    patch: z.array(zEvidenceBulkPatchOperationRequestModel).optional()
});

export const zEvidenceUpdateCaseFilesRequestModel = zEvidenceBulkPatchRequestModel;

export const zEvidenceUpdateEvidenceGroupsRequest = zEvidenceBulkPatchRequestModel;

export const zEvidenceUpdateEvidencesRequestModel = zEvidenceBulkPatchRequestModel;

/**
 * Evidence PreviewReport Request
 */
export const zEvidenceEvidenceRequestModel = z.object({
    id: z.uuid(),
    title: z.string().optional(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

/**
 * Group report request
 */
export const zEvidenceGroupRequestModel = z.object({
    id: z.uuid(),
    code: z.string().min(1),
    name: z.string().min(1),
    description: z.string(),
    type: z.string().min(1),
    capturedFrom: z.iso.datetime(),
    capturedUntil: z.iso.datetime(),
    evidences: z.array(zEvidenceEvidenceRequestModel).min(1),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional()
});

/**
 * Data PreviewReport Request
 */
export const zEvidenceDataRequestModel = z.object({
    groups: z.array(zEvidenceGroupRequestModel).min(1).optional()
});

/**
 * PreviewReport Request
 */
export const zEvidenceCaseFilePreviewReportRequestModel = z.object({
    template: z.string(),
    languageCode: z.string(),
    data: zEvidenceDataRequestModel.optional(),
    additionalData: z.record(z.string(), z.unknown()).optional(),
    metadata: z.record(z.string(), z.string()).optional()
});

/**
 * Report Request
 */
export const zEvidenceCaseFileReportRequestModel = z.object({
    reportId: z.uuid(),
    filename: z.string().optional(),
    template: z.string(),
    languageCode: z.string(),
    data: zEvidenceDataRequestModel.optional(),
    additionalData: z.record(z.string(), z.unknown()).and(z.unknown()).optional(),
    metadata: z.record(z.string(), z.string()).and(z.unknown()).optional(),
    deletionDate: z.iso.datetime().optional()
});

export const zSignatureParticipantRole1 = z.enum([
    'SIGNATORY',
    'OBSERVER',
    'VALIDATOR'
]);

export const zSignatureSignatureRequestBodyContent = z.object({
    body: z.string().optional(),
    subject: z.string().optional(),
    role: zSignatureParticipantRole1.optional(),
    additionalText: z.string().optional()
});

/**
 * Create Signature Request request
 */
export const zSignatureSignatureRequestBodyModel = z.object({
    status: zSignatureSignatureRequestStatusTypeModel.optional(),
    content: zSignatureSignatureRequestBodyContent.optional()
});

/**
 * Create Signature Request request
 */
export const zSignatureCreateSignatureRequestModel = z.object({
    name: z.string().min(1),
    description: z.string().optional(),
    createdBy: z.string().min(1),
    signatureRequestBody: z.array(zSignatureSignatureRequestBodyModel).optional(),
    notifications: z.boolean().optional(),
    language: z.string().optional(),
    uniqueValidator: z.boolean().optional(),
    provider: zSignatureSignatureRequestProvider.optional(),
    senderName: z.string().optional(),
    senderAddress: z.email().optional(),
    closeConfig: zSignatureCloseConfig.optional(),
    webhookUris: z.array(zSignatureWebhookUri).optional()
});

/**
 * Update a Signature Request
 */
export const zSignatureUpdateSignatureRequestModel = z.object({
    name: z.string().optional(),
    description: z.string().optional(),
    createdBy: z.string().optional(),
    notifications: z.boolean().optional(),
    language: z.string().optional(),
    uniqueValidator: z.boolean().optional(),
    provider: zSignatureSignatureRequestProvider.optional(),
    signatureRequestBody: z.array(zSignatureSignatureRequestBodyModel).optional(),
    closeConfig: zSignatureUpdateCloseConfigModel.optional(),
    webhookUris: z.array(zSignatureWebhookUri).optional()
});

export const zSignatureBulkPatchOperation = z.enum(['REPLACE', 'REMOVE']);

export const zSignatureBulkPatchOperationRequestModel = z.object({
    operation: zSignatureBulkPatchOperation,
    path: z.string(),
    value: z.string().optional()
});

export const zSignatureBulkPatchRequestModel = z.object({
    ids: z.array(z.string()).min(1),
    patch: z.array(zSignatureBulkPatchOperationRequestModel).optional()
});

export const zSignatureUpdateSignatureRequestsRequestModel = zSignatureBulkPatchRequestModel;

export const zSignatureTspTimestampViewModel = z.object({
    token: z.string().optional(),
    timestampedAt: z.iso.datetime().optional()
});

export const zSignatureDltTimestampViewModel = z.object({
    blockHash: z.string().optional(),
    transactionHash: z.string().optional(),
    network: z.string().optional(),
    blockExplorerLink: z.string().optional(),
    timestampedAt: z.iso.datetime().optional()
});

export const zSignatureGetEvidenceTimestampsViewModel = z.object({
    tspTimestamps: z.record(z.string(), zSignatureTspTimestampViewModel).optional(),
    dltTimestamps: z.record(z.string(), zSignatureDltTimestampViewModel).optional()
});

export const zSignatureGetEvidenceViewModel = z.object({
    evidenceId: z.uuid().optional(),
    title: z.string().optional(),
    status: zSignatureGetEvidenceStatusViewModel.optional(),
    capturedAt: z.iso.datetime().optional(),
    fileName: z.string().optional(),
    fileSize: z.int().optional(),
    hash: z.string().optional(),
    timestamps: zSignatureGetEvidenceTimestampsViewModel.optional(),
    createdBy: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional()
});

export const zSignatureDocumentDetailViewModel = z.object({
    id: z.uuid().optional(),
    filename: z.string().optional(),
    title: z.string().optional(),
    mimeType: z.string().optional(),
    description: z.string().optional(),
    signatureDeadline: z.iso.datetime().optional(),
    provider: zSignatureDocumentSignatureProvider.optional(),
    signatureType: zSignatureDocumentSignatureType.optional(),
    status: zSignatureDocumentSignatureStatus.optional(),
    observers: z.array(zSignatureObserverViewModel).optional(),
    signatories: z.array(zSignatureSignatoryViewModel).optional(),
    evidence: zSignatureGetEvidenceViewModel.optional(),
    countSignatories: z.int().optional(),
    countObservers: z.int().optional(),
    fileSize: z.int().optional(),
    language: z.string().optional(),
    original: z.boolean().optional(),
    signed: z.boolean().optional(),
    sequence: z.int().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    detached: z.boolean().optional(),
    convertToPdf: z.boolean().optional(),
    legalEntitySigners: z.array(zSignatureLegalEntitySignerViewModel).optional()
});

/**
 * Signature request detail response
 */
export const zSignatureSignatureRequestDetailViewModel = z.object({
    id: z.uuid().optional(),
    status: zSignatureSignatureRequestStatus.optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    cancellationReason: zSignatureCancellationReason.optional(),
    createdBy: z.string().optional(),
    senderName: z.string().optional(),
    senderAddress: z.string().optional(),
    notifications: z.boolean().optional(),
    documents: z.array(zSignatureDocumentDetailViewModel).optional(),
    createdAt: z.iso.datetime().optional(),
    language: z.string().optional(),
    statusHistory: z.array(zSignatureSignatureRequestStatusViewModel).optional(),
    signatureRequestBody: z.array(zSignatureSignatureRequestBodyModel).optional(),
    uniqueValidator: z.boolean().optional(),
    provider: zSignatureSignatureRequestProvider.optional(),
    closeConfig: zSignatureCloseConfig.optional(),
    webhookUris: z.array(zSignatureWebhookUriViewModel).optional()
});

export const zNotificationNotificationType2 = z.enum([
    'NO_RESPONSE',
    'ACCEPTED_OR_NOT',
    'RECEIVED_AGREE',
    'LONG_RESPONSE'
]);

export const zNotificationNotificationSearchNoticemanFilters = z.object({
    type: z.array(zNotificationNotificationType2).nullish()
});

export const zNotificationNotificationSearchEmailFilters = z.object({
    subject: z.string().nullish(),
    sender: z.array(z.string()).nullish(),
    noticeman: zNotificationNotificationSearchNoticemanFilters.nullish()
});

export const zNotificationNotificationSearchFilters = z.object({
    common: zNotificationNotificationSearchCommonFilters.nullish(),
    email: zNotificationNotificationSearchEmailFilters.nullish()
});

export const zNotificationFileTypeModel = z.enum([
    'EVIDENCE',
    'THUMBNAIL',
    'REPORT',
    'REPORT_PACKAGE',
    'TEMPLATE',
    'TEMPORARY_FILE',
    'FONT',
    'NOTIFICATION_ATTACHMENT',
    'SCRIBBLE',
    'CONVERTED'
]);

export const zNotificationNotificationAttachmentStatus = z.enum([
    'WAITING_FILE',
    'READY_TO_SEND',
    'REVIEWED'
]);

export const zNotificationNotificationAttachment = z.object({
    fileId: z.uuid().optional(),
    filename: z.string().optional(),
    hash: z.string().optional(),
    fileType: zNotificationFileTypeModel.optional(),
    attachmentStatus: zNotificationNotificationAttachmentStatus.optional(),
    reviewedAt: z.iso.datetime().optional(),
    mimeType: z.string().optional(),
    fileSize: z.int().optional()
});

export const zNotificationNotificationStateType = z.enum([
    'DRAFT',
    'ACTIVE',
    'DISPATCHED',
    'DISPATCH_FAILED',
    'DELIVERING',
    'ERROR',
    'SENT',
    'RELAYED',
    'BOUNCED',
    'OPEN',
    'READ',
    'ACCEPTED',
    'NOT_ACCEPTED',
    'RECEIVED_CONFORMING',
    'RECEIVED_NON_CONFORMING',
    'ANSWERED',
    'CANCELLED'
]);

export const zNotificationNotificationProviderType = z.enum([
    'SMS',
    'SMTP',
    'NOTICEMAN',
    'NOTICEMAN_AND_WHATSAPP',
    'NOTICEMAN_AND_WHATSAPP_AND_RCS',
    'NOTICEMAN_AND_RCS',
    'WFB',
    'RCS'
]);

export const zNotificationNotificationState = z.object({
    notificationId: z.uuid().optional(),
    registeredAt: z.iso.datetime().optional(),
    state: zNotificationNotificationStateType.optional(),
    provider: zNotificationNotificationProviderType.optional()
});

export const zNotificationNotification = z.object({
    id: z.uuid().optional(),
    requestId: z.uuid().optional(),
    type: zNotificationNotificationType1.optional(),
    senderAddress: z.string().optional(),
    senderName: z.string().optional(),
    senderAddressReplyTo: z.string().optional(),
    recipientAddress: z.string().optional(),
    recipientName: z.string().optional(),
    subject: z.string().optional(),
    content: z.string().optional(),
    notificationAttachments: z.array(zNotificationNotificationAttachment).optional(),
    language: z.string().optional(),
    createdBy: z.string().optional(),
    states: z.array(zNotificationNotificationState).optional(),
    phone: z.string().optional(),
    reminderHours: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    scheduledAt: z.iso.datetime().optional(),
    limitResponse: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    autosend: z.boolean().optional(),
    additionalText: z.string().optional(),
    provider: z.string().optional()
});

export const zNotificationBaseCollectionViewModelNotification = z.object({
    records: z.array(zNotificationNotification).optional(),
    _metadata: zNotificationMetadata.optional()
});

export const zNotificationNotificationSearchCollectionViewModel = zNotificationBaseCollectionViewModelNotification.and(z.object({
    records: z.array(zNotificationNotification).optional()
}));

export const zNotificationActorRequestModel = z.object({
    address: z.email().optional(),
    name: z.string().optional(),
    addressReplyTo: z.email().optional()
});

export const zNotificationUpdateNotificationSmtpRequestModel = z.object({
    sender: zNotificationActorRequestModel,
    subject: z.string().min(1)
});

export const zNotificationNotificationType = z.enum([
    'ACCEPTED_OR_NOT',
    'RECEIVED_AGREE',
    'LONG_RESPONSE',
    'NO_RESPONSE'
]);

export const zNotificationUpdateNotificationNoticemanRequestModel = zNotificationUpdateNotificationSmtpRequestModel.and(z.object({
    notificationType: zNotificationNotificationType.optional(),
    scheduledAt: z.iso.datetime().optional(),
    reminder: z.int().gte(24).lte(720).optional(),
    limitResponse: z.int().gte(0).lte(720).optional()
}));

export const zNotificationUpdateNotificationContentRequestModel = z.object({
    smtp: zNotificationUpdateNotificationSmtpRequestModel.optional(),
    noticeman: zNotificationUpdateNotificationNoticemanRequestModel.optional(),
    provider: z.string().min(1).regex(/SMTP|NOTICEMAN/)
});

/**
 * Update a Request
 */
export const zNotificationUpdateRequestModel = z.object({
    content: z.string().optional(),
    language: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    data: zNotificationUpdateNotificationContentRequestModel.optional()
});

export const zNotificationRecipientType1 = z.enum([
    'TO',
    'CC',
    'BCC'
]);

/**
 * Receiver Noticeman
 */
export const zNotificationAddReceiverNoticemanNotificationRequestModel = z.object({
    provider: z.enum(['NOTICEMAN']),
    type: zNotificationRecipientType1,
    address: z.email().min(1),
    name: z.string().optional(),
    phone: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional()
});

/**
 * Receiver request model
 */
export const zNotificationReceiverNotificationRequestModel = z.discriminatedUnion('provider', [
    zNotificationAddReceiverEmailNotificationRequestModel.extend({ provider: z.literal('Notification_AddReceiverEmailNotificationRequestModel') }),
    zNotificationAddReceiverNoticemanNotificationRequestModel.extend({ provider: z.literal('Notification_AddReceiverNoticemanNotificationRequestModel') }),
    zNotificationAddReceiverSmsNotificationRequestModel.extend({ provider: z.literal('Notification_AddReceiverSmsNotificationRequestModel') }),
    zNotificationAddReceiverWfbNotificationRequestModel.extend({ provider: z.literal('Notification_AddReceiverWfbNotificationRequestModel') })
]);

export const zNotificationAddReceiversNotificationRequestModel = z.object({
    receivers: z.array(zNotificationReceiverNotificationRequestModel).min(1)
});

export const zNotificationNotificationAttachmentModel = z.object({
    filename: z.string().min(1),
    hash: z.string().min(1),
    fileSize: z.int().gte(1).optional()
});

export const zNotificationExternalNotificationAttachmentModel = z.object({
    id: z.string().min(1),
    type: z.string().min(1).regex(/EVIDENCE|REPORT|REPORT_PACKAGE/),
    filename: z.string().min(1),
    hash: z.string().optional()
});

export const zNotificationRcsType = z.enum(['TEXT', 'TEMPLATE']);

export const zNotificationRegisterNotificationRcsRequestModel = z.object({
    receiverAddresses: z.array(z.string()).min(1),
    type: zNotificationRcsType,
    templateId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    templateAttributes: z.record(z.string(), z.string()).optional(),
    auxiliarySmsText: z.string().optional(),
    scheduleDate: z.iso.datetime().optional(),
    priority: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zNotificationRecipientType = z.enum([
    'TO',
    'CC',
    'BCC'
]);

export const zNotificationRecipientActor = zNotificationActorRequestModel.and(z.object({
    type: zNotificationRecipientType.optional(),
    phone: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional()
}));

export const zNotificationRegisterNotificationSmtpRequestModel = z.object({
    sender: zNotificationActorRequestModel.optional(),
    receiver: z.array(zNotificationRecipientActor).min(1),
    subject: z.string().min(1),
    attachments: z.array(zNotificationNotificationAttachmentModel).optional(),
    externalAttachments: z.array(zNotificationExternalNotificationAttachmentModel).optional(),
    template: z.string().optional(),
    parameters: z.record(z.string(), z.string()).optional()
});

export const zNotificationRegisterNotificationNoticemanRequestModel = zNotificationRegisterNotificationSmtpRequestModel.and(z.object({
    notificationType: zNotificationNotificationType,
    scheduledAt: z.iso.datetime().optional(),
    reminder: z.int().gte(24).lte(720).optional(),
    limitResponse: z.int().gte(0).lte(720).optional()
}));

export const zNotificationRegisterNotificationContentRequestModel = z.object({
    smtp: zNotificationRegisterNotificationSmtpRequestModel.optional(),
    noticeman: zNotificationRegisterNotificationNoticemanRequestModel.optional(),
    sms: zNotificationRegisterNotificationSmsRequestModel.optional(),
    wfb: zNotificationRegisterNotificationWhatsappRequestModel.optional(),
    rcs: zNotificationRegisterNotificationRcsRequestModel.optional(),
    provider: z.string().min(1).regex(/SMS|SMTP|NOTICEMAN|WFB|RCS/)
});

export const zNotificationRegisterNotificationV2RequestModel = z.object({
    requestId: z.uuid().optional(),
    content: z.string().optional(),
    language: z.string().min(1),
    data: zNotificationRegisterNotificationContentRequestModel.optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    autosend: z.boolean().optional()
});

export const zEvidenceDeleteCaseFilesBody = zEvidenceBulkDeleteEntityRequestModel;

/**
 * Case files request accepted
 */
export const zEvidenceDeleteCaseFilesResponse = z.void();

export const zEvidenceDeleteEvidenceGroupsBody = zEvidenceBulkDeleteEntityRequestModel;

export const zEvidenceDeleteEvidenceGroupsPath = z.object({
    caseFileId: z.uuid()
});

/**
 * Evidence groups request accepted
 */
export const zEvidenceDeleteEvidenceGroupsResponse = z.void();

export const zEvidenceSearchQuery = z.object({
    filter: zEvidenceSearchCaseFileRequestModel
});

/**
 * Case files retrieved
 */
export const zEvidenceSearchResponse = zEvidenceSearchCaseFileCollectionViewModel;

export const zEvidenceUpdateCaseFilesBody = zEvidenceBulkPatchRequestModel;

/**
 * Case files updated sucessfully
 */
export const zEvidenceUpdateCaseFilesResponse = z.void();

export const zEvidenceCreateCaseFileBody = zEvidenceCreateCaseFileRequestModel;

/**
 * CaseFile created
 */
export const zEvidenceCreateCaseFileResponse = z.record(z.string(), z.unknown());

export const zEvidenceGetCaseFilePath = z.object({
    caseFileId: z.uuid()
});

/**
 * Case file retrieved
 */
export const zEvidenceGetCaseFileResponse = zEvidenceGetCaseFileViewModel;

export const zEvidenceUpdateCaseFileBody = zEvidenceUpdateCaseFileRequestModel;

export const zEvidenceUpdateCaseFilePath = z.object({
    caseFileId: z.uuid()
});

/**
 * Updated successfully
 */
export const zEvidenceUpdateCaseFileResponse = z.void();

export const zEvidenceCreateEvidenceGroupBody = zEvidenceCreateEvidenceGroupRequestModel;

export const zEvidenceCreateEvidenceGroupPath = z.object({
    caseFileId: z.uuid()
});

/**
 * EvidenceGroup created
 */
export const zEvidenceCreateEvidenceGroupResponse = z.record(z.string(), z.unknown());

export const zEvidenceDiscardGroupPath = z.object({
    caseFileId: z.uuid(),
    evidenceGroupId: z.uuid()
});

/**
 * Evidence group discarded successfully
 */
export const zEvidenceDiscardGroupResponse = z.void();

export const zEvidenceGetEvidenceGroupPath = z.object({
    caseFileId: z.uuid(),
    evidenceGroupId: z.uuid()
});

/**
 * Evidence group retrieved
 */
export const zEvidenceGetEvidenceGroupResponse = zEvidenceEvidenceGroupViewModel;

export const zEvidenceUpdateEvidenceGroupBody = zEvidenceUpdateEvidenceGroupRequest;

export const zEvidenceUpdateEvidenceGroupPath = z.object({
    caseFileId: z.uuid(),
    evidenceGroupId: z.uuid()
});

/**
 * Evidence Group updated correctly
 */
export const zEvidenceUpdateEvidenceGroupResponse = z.record(z.string(), z.unknown());

export const zEvidenceCloseEvidenceGroupBody = zEvidenceCloseEvidenceGroupRequestModel;

export const zEvidenceCloseEvidenceGroupPath = z.object({
    caseFileId: z.uuid(),
    evidenceGroupId: z.uuid()
});

/**
 * EvidenceGroup close request accepted
 */
export const zEvidenceCloseEvidenceGroupResponse = z.record(z.string(), z.unknown());

export const zEvidenceRegisterEvidenceBody = zEvidenceRegisterEvidenceRequestModel;

export const zEvidenceRegisterEvidencePath = z.object({
    caseFileId: z.uuid(),
    evidenceGroupId: z.uuid()
});

/**
 * Evidence registered successfully
 */
export const zEvidenceRegisterEvidenceResponse = zEvidenceRegisterEvidenceResponseModel;

export const zEvidenceDeleteEvidencePath = z.object({
    caseFileId: z.uuid(),
    evidenceGroupId: z.uuid(),
    evidenceId: z.uuid()
});

/**
 * Evidence deleted
 */
export const zEvidenceDeleteEvidenceResponse = z.void();

export const zEvidenceGetEvidencePath = z.object({
    caseFileId: z.uuid(),
    evidenceGroupId: z.uuid(),
    evidenceId: z.uuid()
});

/**
 * Evidence got
 */
export const zEvidenceGetEvidenceResponse = zEvidenceGetEvidenceViewModel;

export const zEvidenceCreateDownloadUrlPath = z.object({
    caseFileId: z.uuid(),
    evidenceGroupId: z.uuid(),
    evidenceId: z.uuid()
});

export const zEvidenceCreateUploadUrlBody = z.object({
    requestModel: zEvidenceNewUploadUrlRequestModel.optional()
});

export const zEvidenceCreateUploadUrlPath = z.object({
    caseFileId: z.uuid(),
    evidenceGroupId: z.uuid(),
    evidenceId: z.uuid()
});

export const zEvidenceThumbnailUrlPath = z.object({
    caseFileId: z.uuid(),
    groupId: z.uuid(),
    evidenceId: z.uuid(),
    thumbnailSize: z.string()
});

/**
 * Thumbnail URL location and expiration
 */
export const zEvidenceThumbnailUrlResponse = zEvidenceDownloadUrlModel1;

export const zEvidenceAssignRelationshipBody = zEvidenceAssignRelationshipRequestModel;

export const zEvidenceAssignRelationshipPath = z.object({
    caseFileId: z.uuid()
});

export const zEvidenceObtainReportPreviewBody = zEvidenceCaseFilePreviewReportRequestModel;

export const zEvidenceObtainReportPreviewPath = z.object({
    caseFileId: z.uuid()
});

/**
 * Generated ReportPreview
 */
export const zEvidenceObtainReportPreviewResponse = z.record(z.string(), z.unknown());

export const zEvidenceObtainSignedReportBody = zEvidenceCaseFileReportRequestModel;

export const zEvidenceObtainSignedReportPath = z.object({
    caseFileId: z.uuid()
});

/**
 * Generated signed report
 */
export const zEvidenceObtainSignedReportResponse = z.record(z.string(), z.unknown());

export const zEvidenceUpdateReportBody = zEvidenceUpdateCaseFileReportRequestModel;

export const zEvidenceUpdateReportPath = z.object({
    caseFileId: z.uuid(),
    reportId: z.uuid()
});

/**
 * Updated successfully
 */
export const zEvidenceUpdateReportResponse = z.void();

export const zEvidenceReportPdfPath = z.object({
    caseFileId: z.uuid(),
    reportId: z.uuid()
});

/**
 * Report PDF URL information
 */
export const zEvidenceReportPdfResponse = zEvidenceDownloadUrlModel;

export const zEvidenceReportZipPath = z.object({
    caseFileId: z.uuid(),
    reportId: z.uuid()
});

/**
 * Report ZIP URL information
 */
export const zEvidenceReportZipResponse = zEvidenceDownloadUrlModel;

export const zEvidenceUpdateCaseFileStatusBody = zEvidenceUpdateCaseFileStatusRequestModel;

export const zEvidenceUpdateCaseFileStatusPath = z.object({
    caseFileId: z.uuid()
});

/**
 * Updated successfully
 */
export const zEvidenceUpdateCaseFileStatusResponse = z.void();

export const zEvidenceObtainReportPreview1Body = zEvidenceChatPreviewReportRequestModel;

export const zEvidenceObtainReportPreview1Path = z.object({
    chatId: z.uuid()
});

/**
 * Generated ReportPreview
 */
export const zEvidenceObtainReportPreview1Response = z.record(z.string(), z.unknown());

export const zEvidenceSearch1Query = z.object({
    filter: zEvidenceEvidenceGroupSearch
});

/**
 * Evidence Groups returned
 */
export const zEvidenceSearch1Response = zEvidenceSearchEvidenceGroupCollectionViewModel;

export const zEvidenceUpdateEvidenceGroupsBody = zEvidenceBulkPatchRequestModel;

/**
 * Evidence groups updated successfully
 */
export const zEvidenceUpdateEvidenceGroupsResponse = z.void();

export const zEvidenceSearch2Query = z.object({
    filter: zEvidenceSearchEvidenceRequestModel
});

/**
 * Evidences returned
 */
export const zEvidenceSearch2Response = zEvidenceSearchEvidenceCollectionViewModel;

export const zEvidenceUpdateEvidenceBody = zEvidenceBulkPatchRequestModel;

/**
 * Evidences updated sucessfully
 */
export const zEvidenceUpdateEvidenceResponse = z.void();

export const zEvidenceRegisterEvidence1Body = zEvidenceRegisterEvidenceRequestModel;

/**
 * Evidence registered successfully
 */
export const zEvidenceRegisterEvidence1Response = zEvidenceRegisterEvidenceResponseModel;

export const zEvidenceDeleteEvidence1Path = z.object({
    evidenceId: z.uuid()
});

/**
 * Evidence deleted
 */
export const zEvidenceDeleteEvidence1Response = z.void();

export const zEvidenceGetEvidence1Path = z.object({
    evidenceId: z.uuid()
});

/**
 * Evidence got
 */
export const zEvidenceGetEvidence1Response = zEvidenceGetEvidenceViewModel;

export const zEvidenceUpdateEvidence1Body = zEvidenceUpdateEvidenceRequestModel;

export const zEvidenceUpdateEvidence1Path = z.object({
    evidenceId: z.uuid()
});

/**
 * Evidence updated
 */
export const zEvidenceUpdateEvidence1Response = z.void();

export const zEvidenceCreateDownloadUrl1Path = z.object({
    evidenceId: z.uuid()
});

export const zEvidenceCreateUploadUrl1Body = zEvidenceNewUploadUrlRequestModel;

export const zEvidenceCreateUploadUrl1Path = z.object({
    evidenceId: z.string()
});

export const zEvidenceCreateUploadUrl2Body = zEvidenceUploadUrlTemporaryFileHttpRequestModel;

export const zEvidenceDeleteReportPath = z.object({
    reportId: z.uuid()
});

/**
 * Report deleted
 */
export const zEvidenceDeleteReportResponse = z.void();

export const zEvidenceGetReportPdfPath = z.object({
    reportId: z.uuid()
});

/**
 * The URL and expiration to download the required report
 */
export const zEvidenceGetReportPdfResponse = zEvidenceDownloadUrlModel;

export const zEvidenceGetReportZipPath = z.object({
    reportId: z.uuid()
});

/**
 * The URL and expiration to download the required report
 */
export const zEvidenceGetReportZipResponse = zEvidenceDownloadUrlModel;

export const zEvidenceStartMultipartUploadBody = zEvidenceStartMultipartUploadRequestModel;

export const zEvidenceStartMultipartUploadPath = z.object({
    evidenceId: z.uuid(),
    fileName: z.string()
});

export const zSignatureDeleteBulkSignatureRequestsBody = zSignatureBulkDeleteSignatureRequestRequestModel;

/**
 * Signature requests delete request accepted
 */
export const zSignatureDeleteBulkSignatureRequestsResponse = z.void();

export const zSignatureAddValidatorBody = zSignatureAddValidatorRequestModel;

export const zSignatureAddValidatorPath = z.object({
    documentId: z.uuid(),
    signatoryId: z.uuid()
});

/**
 * Validator created
 */
export const zSignatureAddValidatorResponse = zSignatureValidatorViewModel;

export const zSignatureDeleteValidatorPath = z.object({
    documentId: z.uuid(),
    signatoryId: z.uuid(),
    validatorId: z.uuid()
});

/**
 * Validator deleted
 */
export const zSignatureDeleteValidatorResponse = z.void();

export const zSignatureGetReportPdfPath = z.object({
    reportId: z.uuid(),
    documentId: z.uuid()
});

/**
 * The URL and expiration to download the required report
 */
export const zSignatureGetReportPdfResponse = zSignatureFileDocumentDownloadUrlViewModel;

export const zSignatureGetReportZipPath = z.object({
    reportId: z.uuid(),
    documentId: z.uuid()
});

/**
 * The URL and expiration to download the required report
 */
export const zSignatureGetReportZipResponse = zSignatureFileDocumentDownloadUrlViewModel;

export const zSignatureGetSignatureRequestsQuery = z.object({
    ids: z.array(z.uuid()).nullish(),
    names: z.array(z.string()).nullish(),
    creators: z.array(z.string()).nullish(),
    statuses: z.array(zSignatureSignatureRequestStatus).nullish(),
    cancellationReasons: z.array(zSignatureCancellationReason).nullish(),
    dateFrom: z.string().nullish(),
    dateTo: z.string().nullish(),
    signatureTypes: z.array(zSignatureDocumentSignatureType).nullish(),
    providers: z.array(zSignatureDocumentSignatureProvider).nullish(),
    emailSignatories: z.array(z.string()).nullish(),
    emailObservers: z.array(z.string()).nullish(),
    hashes: z.array(z.string()).nullish(),
    closeCondition: zSignatureCloseConditionViewModel.nullish(),
    closeAtFrom: z.string().nullish(),
    closeAtTo: z.string().nullish(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    sort: z.array(z.string()).nullish()
});

/**
 * Signature requests obtained successfully
 */
export const zSignatureGetSignatureRequestsResponse = z.array(zSignatureSignatureRequestViewModel1);

export const zSignatureUpdateSignatureRequestsBody = zSignatureBulkPatchRequestModel;

/**
 * Signature requests updated successfully
 */
export const zSignatureUpdateSignatureRequestsResponse = z.void();

export const zSignatureCreateSignatureRequestBody = zSignatureCreateSignatureRequestModel;

/**
 * Signature request created
 */
export const zSignatureCreateSignatureRequestResponse = zSignatureSignatureRequestViewModel;

export const zSignatureDeleteSignatureRequestPath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * Signature request deleted
 */
export const zSignatureDeleteSignatureRequestResponse = z.void();

export const zSignatureGetSignatureRequestPath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * Signature request obtained successfully
 */
export const zSignatureGetSignatureRequestResponse = z.array(zSignatureSignatureRequestDetailViewModel);

export const zSignatureUpdateBody = zSignatureUpdateSignatureRequestModel;

export const zSignatureUpdatePath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * Signature request updated
 */
export const zSignatureUpdateResponse = z.void();

export const zSignatureActivatePath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * activate 200 response
 */
export const zSignatureActivateResponse = zSignatureActivateSignatureRequestViewModel;

export const zSignatureCancelPath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * Signature request cancelled successfully
 */
export const zSignatureCancelResponse = zSignatureCancelSignatureRequestViewModel;

export const zSignatureWellSignedDocumentGenerationPath = z.object({
    signatureRequestId: z.string()
});

/**
 * Process generated successfully
 */
export const zSignatureWellSignedDocumentGenerationResponse = z.record(z.string(), z.unknown());

export const zSignatureClosePath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * Signature request closed successfully
 */
export const zSignatureCloseResponse = zSignatureCloseSignatureRequestViewModel;

export const zSignatureGetDocumentsPath = z.object({
    signatureRequestId: z.uuid()
});

export const zSignatureGetDocumentsQuery = z.object({
    ids: z.array(z.uuid()).nullish(),
    filenames: z.array(z.string()).nullish(),
    titles: z.array(z.string()).nullish(),
    signatureTypes: z.array(zSignatureDocumentSignatureType).nullish(),
    providers: z.array(zSignatureDocumentSignatureProvider).nullish(),
    statuses: z.array(zSignatureDocumentSignatureStatus).nullish(),
    hashes: z.array(z.string()).nullish(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    sort: z.array(z.string()).nullish()
});

/**
 * Signature request documents obtained successfully
 */
export const zSignatureGetDocumentsResponse = z.array(zSignatureGetDocumentsViewModel);

export const zSignatureAddDocumentBody = zSignatureAddDocumentRequestModel;

export const zSignatureAddDocumentPath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * Document added successfully
 */
export const zSignatureAddDocumentResponse = zSignatureAddDocumentViewModel;

export const zSignatureStartMultipartBody = zSignatureAddDocumentRequestModel;

export const zSignatureStartMultipartPath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * Document multipart started successfully
 */
export const zSignatureStartMultipartResponse = zSignatureDocumentMultipartViewModel;

export const zSignatureDeleteDocumentPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

/**
 * Document deleted
 */
export const zSignatureDeleteDocumentResponse = z.void();

export const zSignatureGetDocumentPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

/**
 * Document obtained successfully
 */
export const zSignatureGetDocumentResponse = zSignatureDocumentDetailViewModel;

export const zSignatureGenerateDownloadConvertedLinkPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

/**
 * Document converted link generated successfully
 */
export const zSignatureGenerateDownloadConvertedLinkResponse = zSignatureFileDocumentDownloadUrlViewModel;

export const zSignatureGetDownloadUrlPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

export const zSignatureGenerateDownloadLinkPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

/**
 * Document final link generated successfully
 */
export const zSignatureGenerateDownloadLinkResponse = zSignatureFileDocumentSignedDownloadUrlViewModel;

export const zSignatureGetUploadUrlPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

/**
 * Get a document upload link
 */
export const zSignatureGetUploadUrlResponse = zSignatureGetUploadUrlViewModel;

export const zSignatureGetObserversPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

export const zSignatureGetObserversQuery = z.object({
    ids: z.array(z.uuid()).nullish(),
    emails: z.array(z.string()).nullish(),
    hasCoordinates: z.boolean().nullish(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    sort: z.array(z.string()).nullish()
});

/**
 * Document observers obtained successfully
 */
export const zSignatureGetObserversResponse = z.array(zSignatureObserverViewModel);

export const zSignatureAddObserverBody = zSignatureAddObserverRequestModel;

export const zSignatureAddObserverPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

/**
 * Observer created
 */
export const zSignatureAddObserverResponse = zSignatureObserverViewModel;

export const zSignatureDeleteObserverPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    observerId: z.uuid()
});

/**
 * Observer deleted
 */
export const zSignatureDeleteObserverResponse = z.void();

export const zSignatureUpdate1Body = zSignatureUpdateObserverRequestModel;

export const zSignatureUpdate1Path = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    observerId: z.uuid()
});

/**
 * Observer update_1
 */
export const zSignatureUpdate1Response = zSignatureObserverViewModel;

export const zSignatureGetFinalReportPdfPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

export const zSignatureGetFinalReportZipPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

export const zSignatureGenerateDownloadLink1Path = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    reportId: z.uuid()
});

/**
 * Document interim link generated successfully
 */
export const zSignatureGenerateDownloadLink1Response = zSignatureFileDocumentSignedDownloadUrlViewModel;

export const zSignatureUpdateSequenceBody = zSignatureUpdateDocumentSequenceRequestModel;

export const zSignatureUpdateSequencePath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

/**
 * Sequence updated
 */
export const zSignatureUpdateSequenceResponse = z.void();

export const zSignatureGetSignatoriesPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

export const zSignatureGetSignatoriesQuery = z.object({
    ids: z.array(z.uuid()).nullish(),
    emails: z.array(z.string()).nullish(),
    hasCoordinates: z.boolean().nullish(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    sort: z.array(z.string()).nullish()
});

/**
 * Document signatories obtained successfully
 */
export const zSignatureGetSignatoriesResponse = z.array(zSignatureSignatoryViewModel);

export const zSignatureAddSignatoryBody = zSignatureAddSignatoryRequestModel;

export const zSignatureAddSignatoryPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid()
});

/**
 * Signatory created
 */
export const zSignatureAddSignatoryResponse = zSignatureSignatoryViewModel;

export const zSignatureDeleteSignatoryPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    signatoryId: z.uuid()
});

/**
 * Signatory deleted
 */
export const zSignatureDeleteSignatoryResponse = z.void();

export const zSignatureUpdate2Body = zSignatureUpdateSignatoryRequestModel;

export const zSignatureUpdate2Path = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    signatoryId: z.uuid()
});

/**
 * Signatory update_2
 */
export const zSignatureUpdate2Response = zSignatureSignatoryViewModel;

export const zSignatureUpdateCoordinatesBody = zSignatureUpdateSignatoryCoordinatesRequestModel;

export const zSignatureUpdateCoordinatesPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    signatoryId: z.uuid()
});

/**
 * Coordinates updated
 */
export const zSignatureUpdateCoordinatesResponse = z.void();

export const zSignatureResendToSignatoryPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    signatoryId: z.uuid()
});

export const zSignatureUpdateSequence1Body = zSignatureUpdateSignatorySequenceRequestModel;

export const zSignatureUpdateSequence1Path = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    signatoryId: z.uuid()
});

/**
 * Sequence updated
 */
export const zSignatureUpdateSequence1Response = z.void();

export const zSignatureUpdate3Body = zSignatureUpdateValidatorRequestModel;

export const zSignatureUpdate3Path = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    signatoryId: z.uuid(),
    validatorId: z.uuid()
});

/**
 * Validator update_3
 */
export const zSignatureUpdate3Response = zSignatureValidatorViewModel;

export const zSignatureResendToValidatorPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    signatoryId: z.uuid(),
    validatorId: z.uuid()
});

export const zSignatureCancelMultipartPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    uploadId: z.string()
});

/**
 * Document multipart cancelled successfully
 */
export const zSignatureCancelMultipartResponse = z.void();

export const zSignatureGetMultipartUploadLinkPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    uploadId: z.string()
});

export const zSignatureGetMultipartUploadLinkQuery = z.object({
    partNumber: z.int().gte(1).lte(10000)
});

/**
 * Upload link obtained successfully
 */
export const zSignatureGetMultipartUploadLinkResponse = zSignatureUploadLinkOutputModel;

export const zSignatureCompleteMultipartPath = z.object({
    signatureRequestId: z.uuid(),
    documentId: z.uuid(),
    uploadId: z.string()
});

export const zSignatureCompleteMultipartQuery = z.object({
    partCounts: z.int().gte(1).lte(10000)
});

export const zSignatureDraftPath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * draft 200 response
 */
export const zSignatureDraftResponse = zSignatureDraftSignatureRequestViewModel;

export const zSignatureGenerateBody = zSignatureSignatureRequestReportRequestModel;

export const zSignatureGeneratePath = z.object({
    signatureRequestId: z.uuid()
});

/**
 * Document report obtain successfully
 */
export const zSignatureGenerateResponse = z.array(zSignatureSignatureRequestReportViewModel);

export const zSignatureResendPath = z.object({
    signatureRequestId: z.uuid()
});

export const zSignatureGetSignatories1Path = z.object({
    signatureRequestId: z.uuid()
});

export const zSignatureGetSignatories1Query = z.object({
    ids: z.array(z.uuid()).nullish(),
    emails: z.array(z.string()).nullish(),
    documentId: z.uuid().nullish(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    hasCoordinates: z.boolean().nullish(),
    sort: z.array(z.string()).nullish()
});

/**
 * Signatories obtained successfully
 */
export const zSignatureGetSignatories1Response = z.array(zSignatureSignatoryViewModel);

export const zSignatureGetValidatorsPath = z.object({
    signatureRequestId: z.uuid()
});

export const zSignatureGetValidatorsQuery = z.object({
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    sort: z.array(z.string()).nullish()
});

/**
 * Document validators obtained successfully
 */
export const zSignatureGetValidatorsResponse = z.array(zSignatureListValidatorsViewModel);

export const zNotificationDeleteNotificationsBody = zNotificationBulkDeleteEntityRequestModel;

/**
 * Notifications delete request accepted
 */
export const zNotificationDeleteNotificationsResponse = z.void();

export const zNotificationSearchQuery = z.object({
    ids: z.array(z.uuid()).nullish(),
    requestId: z.uuid().nullish(),
    states: z.array(zNotificationNotificationStateType1).nullish(),
    filters: zNotificationNotificationSearchFilters.nullish(),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    size: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    sort: z.array(z.string()).nullish()
});

/**
 * Notifications returned
 */
export const zNotificationSearchResponse = zNotificationNotificationSearchCollectionViewModel;

export const zNotificationDeletePath = z.object({
    requestId: z.string()
});

/**
 * Request deleted successfully
 */
export const zNotificationDeleteResponse = z.void();

export const zNotificationUpdateBody = zNotificationUpdateRequestModel;

export const zNotificationUpdatePath = z.object({
    requestId: z.uuid()
});

/**
 * Request updated successfully
 */
export const zNotificationUpdateResponse = z.void();

export const zNotificationActivateNotificationRequestPath = z.object({
    requestId: z.uuid()
});

export const zNotificationAddRequestAttachmentBody = zNotificationAddRequestAttachmentRequestModel;

export const zNotificationAddRequestAttachmentPath = z.object({
    requestId: z.string()
});

/**
 * Attachments added successfully
 */
export const zNotificationAddRequestAttachmentResponse = zNotificationAddRequestAttachmentViewModel;

export const zNotificationDeleteAttachmentPath = z.object({
    requestId: z.string(),
    fileId: z.string()
});

/**
 * Attachment deleted successfully
 */
export const zNotificationDeleteAttachmentResponse = z.void();

export const zNotificationDeleteNotificationBody = zNotificationDeleteRequestReceiver;

export const zNotificationDeleteNotificationPath = z.object({
    requestId: z.uuid()
});

/**
 * Notification deleted successfully
 */
export const zNotificationDeleteNotificationResponse = z.void();

export const zNotificationAddReceiversBody = zNotificationAddReceiversNotificationRequestModel;

export const zNotificationAddReceiversPath = z.object({
    requestId: z.uuid()
});

/**
 * Receivers added successfully
 */
export const zNotificationAddReceiversResponse = zNotificationReceiversNotificationViewModel;

export const zNotificationRegisterNotificationBody = zNotificationRegisterNotificationV2RequestModel;

/**
 * Notification created successfully
 */
export const zNotificationRegisterNotificationResponse = zNotificationRegisterNotificationViewModel;

export const zNotificationGetNotificationPath = z.object({
    notificationId: z.uuid()
});

/**
 * Notification detail got
 */
export const zNotificationGetNotificationResponse = zNotificationNotificationDetailViewModel;

export const zNotificationUpdate1Body = zNotificationUpdateOnLiveNotificationRequestModel;

export const zNotificationUpdate1Path = z.object({
    notificationId: z.uuid()
});

/**
 * Notification update_1d successfully
 */
export const zNotificationUpdate1Response = zNotificationUpdateOnLiveNotificationViewModel;

export const zNotificationCancelPath = z.object({
    notificationId: z.uuid()
});

export const zNotificationCloneBody = zNotificationCloneNotificationRequestModel;

export const zNotificationClonePath = z.object({
    notificationId: z.uuid()
});

/**
 * Notification cloned successfully
 */
export const zNotificationCloneResponse = zNotificationCloneNotificationViewModel;

export const zNotificationResendPath = z.object({
    notificationId: z.uuid()
});

/**
 * Notification resent successfully
 */
export const zNotificationResendResponse = zNotificationResendNotificationViewModel;

export const zNotificationGenerateReportBody = zNotificationGenerateNotificationReportRequestModel;

/**
 * Generated report
 */
export const zNotificationGenerateReportResponse = zNotificationNotificationReportViewModel;

export const zNotificationGetReportPdfPath = z.object({
    reportId: z.uuid()
});

/**
 * The URL and expiration to download the required report
 */
export const zNotificationGetReportPdfResponse = zNotificationFileDocumentDownloadUrlViewModel;

export const zNotificationGetDownloadUrlPath = z.object({
    requestId: z.uuid(),
    attachmentId: z.uuid()
});

export const zNotificationCreateUploadUrlBody = zNotificationUploadNotificationAttachmentModel;

export const zNotificationCreateUploadUrlPath = z.object({
    requestId: z.uuid(),
    attachmentId: z.uuid()
});

/**
 * Upload url created
 */
export const zNotificationCreateUploadUrlResponse = zNotificationUploadNotificationAttachmentUrlViewModel;
