// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-ead-factory (1.0.15)
// Architecture: REST-direct (Epic 12 ADR 0008) — Bearer token fetched by the node.

import {
  ICredentialTestRequest,
  ICredentialType,
  INodeProperties,
} from 'n8n-workflow';

export class EadFactoryApi implements ICredentialType {
  name = 'eadFactoryApi';
  displayName = 'EAD Factory API';
  documentationUrl = 'https://eadtrust.example.com/onboarding';

  properties: INodeProperties[] = [
    {
      displayName: 'API Base URL',
      name: 'baseUrl',
      type: 'string',
      default: '',
      description: 'Base URL of the EAD Factory REST API. Leave as-is for the production environment.',
    },
    {
      displayName: 'Evidence API Base URL',
      name: 'apiBaseUrl',
      type: 'string',
      default: '',
      description: "The base URL for the Evidence Manager API provided by EAD Factory.",
    },
    {
      displayName: 'Full Flow Base Email',
      name: 'fullFlowEmailBase',
      type: 'string',
      default: '',
      description: "Base email address used to generate participant addresses in the full signature flow.",
    },
    {
      displayName: 'Full Flow File Path',
      name: 'fullFlowFilePath',
      type: 'string',
      default: '',
      description: "Default local file path used when running the full signature flow.",
    },
    {
      displayName: 'HTTP Port',
      name: 'httpPort',
      type: 'string',
      default: '',
      description: "Port number the MCP server listens on when running in HTTP transport mode.",
    },
    {
      displayName: 'Okta Client ID',
      name: 'oktaClientId',
      type: 'string',
      default: '',
      description: "Client ID for your Okta application, obtained from your EAD Factory onboarding credentials.",
    },
    {
      displayName: 'Okta Client Secret',
      name: 'oktaClientSecret',
      type: 'string',
      typeOptions: { password: true },
      default: '',
      description: "Client secret for your Okta application, obtained from your EAD Factory onboarding credentials.",
    },
    {
      displayName: 'Okta Scope',
      name: 'oktaScope',
      type: 'string',
      default: '',
      description: "OAuth scope(s) requested when authenticating with Okta for EAD Factory API access.",
    },
    {
      displayName: 'Okta Token URL',
      name: 'oktaTokenUrl',
      type: 'string',
      default: '',
      description: "Okta token endpoint URL used to obtain access tokens via the client credentials flow.",
    },
    {
      displayName: 'Poll Interval (ms)',
      name: 'pollIntervalMs',
      type: 'string',
      default: '',
      description: "Milliseconds to wait between status checks when polling for evidence completion.",
    },
    {
      displayName: 'Max Poll Attempts',
      name: 'pollMaxAttempts',
      type: 'string',
      default: '',
      description: "Maximum number of status polling attempts before the evidence operation times out.",
    },
    {
      displayName: 'Signature API Base URL',
      name: 'signatureApiBaseUrl',
      type: 'string',
      default: '',
      description: "The base URL for the Signature Manager API provided by EAD Factory.",
    },
    {
      displayName: 'Transport Mode',
      name: 'transport',
      type: 'string',
      default: '',
      description: "Set to stdio for local use or http for remote deployment with Bearer token authentication.",
    },
  ];

  test: ICredentialTestRequest = {
    request: {
      baseURL: '={{$credentials.oktaTokenUrl}}',
      url: '',
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'grant_type=client_credentials&client_id={{$credentials.oktaClientId}}&client_secret={{$credentials.oktaClientSecret}}&scope={{$credentials.oktaScope}}',
    },
  };
}
