// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-ead-factory (1.0.14)
// Architecture: REST-direct (Epic 12 ADR 0008) — Bearer token fetched by the node.

import {
  ICredentialTestRequest,
  ICredentialType,
  INodeProperties,
} from 'n8n-workflow';

export class EadFactoryApi implements ICredentialType {
  name = 'eadFactoryApi';
  displayName = 'EAD Factory API';
  documentationUrl = 'https://eadtrust.example.com/onboarding';

  properties: INodeProperties[] = [
    {
      displayName: 'API Base URL',
      name: 'baseUrl',
      type: 'string',
      default: '',
      description: 'Base URL of the EAD Factory REST API. Leave as-is for the production environment.',
    },
    {
      displayName: 'Evidence API Base URL',
      name: 'API_BASE_URL',
      type: 'string',
      default: '',
      description: "The base URL of your EAD Factory Evidence Manager API endpoint.",
    },
    {
      displayName: 'Full Flow Email Base',
      name: 'FULL_FLOW_EMAIL_BASE',
      type: 'string',
      default: '',
      description: "The base email address used to generate participant addresses in full-flow signature requests.",
    },
    {
      displayName: 'Full Flow File Path',
      name: 'FULL_FLOW_FILE_PATH',
      type: 'string',
      default: '',
      description: "The default local file path used when running a full-flow signature request automatically.",
    },
    {
      displayName: 'HTTP Port',
      name: 'HTTP_PORT',
      type: 'string',
      default: '',
      description: "The port number the MCP server listens on when running in HTTP transport mode.",
    },
    {
      displayName: 'Okta Client ID',
      name: 'OKTA_CLIENT_ID',
      type: 'string',
      default: '',
      description: "The client ID of your Okta application, obtained from your EAD Factory onboarding credentials.",
    },
    {
      displayName: 'Okta Client Secret',
      name: 'OKTA_CLIENT_SECRET',
      type: 'string',
      typeOptions: { password: true },
      default: '',
      description: "The client secret of your Okta application, obtained from your EAD Factory onboarding credentials.",
    },
    {
      displayName: 'Okta Scope',
      name: 'OKTA_SCOPE',
      type: 'string',
      default: '',
      description: "The OAuth scope string required by your Okta application for EAD Factory API access.",
    },
    {
      displayName: 'Okta Token URL',
      name: 'OKTA_TOKEN_URL',
      type: 'string',
      default: '',
      description: "The Okta token endpoint URL used to obtain access tokens via the client credentials flow.",
    },
    {
      displayName: 'Poll Interval (ms)',
      name: 'POLL_INTERVAL_MS',
      type: 'string',
      default: '',
      description: "Milliseconds to wait between status checks when polling for evidence completion.",
    },
    {
      displayName: 'Poll Max Attempts',
      name: 'POLL_MAX_ATTEMPTS',
      type: 'string',
      default: '',
      description: "Maximum number of polling attempts before giving up on an evidence status check.",
    },
    {
      displayName: 'Signature API Base URL',
      name: 'SIGNATURE_API_BASE_URL',
      type: 'string',
      default: '',
      description: "The base URL of your EAD Factory Signature Manager API endpoint.",
    },
    {
      displayName: 'Transport Mode',
      name: 'TRANSPORT',
      type: 'string',
      default: '',
      description: "Set to stdio for local use or http for remote deployment with bearer token authentication.",
    },
  ];

  test: ICredentialTestRequest = {
    request: {
      baseURL: '={{$credentials.OKTA_TOKEN_URL}}',
      url: '',
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'grant_type=client_credentials&client_id={{$credentials.OKTA_CLIENT_ID}}&client_secret={{$credentials.OKTA_CLIENT_SECRET}}&scope={{$credentials.OKTA_SCOPE}}',
    },
  };
}
