// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-ead-factory (1.2.1)
// Architecture: REST-direct (Epic 12 ADR 0008) — Bearer token fetched by the node.

import {
  ICredentialTestRequest,
  ICredentialType,
  INodeProperties,
} from 'n8n-workflow';

export class EadFactoryApi implements ICredentialType {
  name = 'eadFactoryApi';
  displayName = 'EAD Factory API';
  documentationUrl = 'https://api.int.gcloudfactory.com';

  properties: INodeProperties[] = [
    {
      displayName: 'API Base URL',
      name: 'baseUrl',
      type: 'string',
      default: '',
      description: 'Base URL of the EAD Factory REST API. Leave as-is for the production environment.',
    },
    {
      displayName: 'OAuth Token URL',
      name: 'mcpSvcTokenUrl',
      type: 'string',
      default: '',
      description: "Token endpoint URL for the OAuth2 client_credentials flow",
    },
    {
      displayName: 'Client ID',
      name: 'mcpSvcClientId',
      type: 'string',
      default: '',
      description: "OAuth2 client_credentials client ID",
    },
    {
      displayName: 'Client Secret',
      name: 'mcpSvcClientSecret',
      type: 'string',
      typeOptions: { password: true },
      default: '',
      description: "OAuth2 client_credentials client secret (See https://digitaltrust.gcloudfactory.com for credential acquisition.)",
    },
    {
      displayName: 'Scope',
      name: 'mcpSvcScope',
      type: 'string',
      default: '',
      description: "Optional OAuth2 scope for the service-account token request",
    },
  ];

  test: ICredentialTestRequest = {
    request: {
      baseURL: '={{$credentials.mcpSvcTokenUrl}}',
      url: '',
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: {
        grant_type: 'client_credentials',
        client_id: '={{$credentials.mcpSvcClientId}}',
        client_secret: '={{$credentials.mcpSvcClientSecret}}',
        scope: '={{$credentials.mcpSvcScope}}',
      },
    },
  };
}
