// Auto-generated by @suite/generator. Do not edit.
// MCP server entry point for EAD Factory

import { createServer } from "./core/server.js";
import { evidence_case_file_delete_bulk } from "./tools/evidence_case_file_delete_bulk.js";
import { evidence_case_file_search } from "./tools/evidence_case_file_search.js";
import { evidence_case_file_create } from "./tools/evidence_case_file_create.js";
import { evidence_case_file_update_bulk } from "./tools/evidence_case_file_update_bulk.js";
import { evidence_case_file_get } from "./tools/evidence_case_file_get.js";
import { evidence_case_file_update } from "./tools/evidence_case_file_update.js";
import { evidence_case_file_relationship_assign } from "./tools/evidence_case_file_relationship_assign.js";
import { evidence_case_file_report_preview } from "./tools/evidence_case_file_report_preview.js";
import { evidence_case_file_report_generate } from "./tools/evidence_case_file_report_generate.js";
import { evidence_case_file_report_update } from "./tools/evidence_case_file_report_update.js";
import { evidence_case_file_report_pdf_url_get } from "./tools/evidence_case_file_report_pdf_url_get.js";
import { evidence_case_file_report_zip_url_get } from "./tools/evidence_case_file_report_zip_url_get.js";
import { evidence_case_file_status_update } from "./tools/evidence_case_file_status_update.js";
import { evidence_report_delete } from "./tools/evidence_report_delete.js";
import { evidence_group_evidence_register } from "./tools/evidence_group_evidence_register.js";
import { evidence_group_evidence_get } from "./tools/evidence_group_evidence_get.js";
import { evidence_group_evidence_delete } from "./tools/evidence_group_evidence_delete.js";
import { evidence_group_evidence_download_url_create } from "./tools/evidence_group_evidence_download_url_create.js";
import { evidence_group_evidence_upload_url_create } from "./tools/evidence_group_evidence_upload_url_create.js";
import { evidence_thumbnail_url_get } from "./tools/evidence_thumbnail_url_get.js";
import { evidence_search } from "./tools/evidence_search.js";
import { generate_evidence } from "./tools/generate_evidence.js";
import { evidence_update_bulk } from "./tools/evidence_update_bulk.js";
import { get_evidence } from "./tools/get_evidence.js";
import { evidence_delete } from "./tools/evidence_delete.js";
import { evidence_update } from "./tools/evidence_update.js";
import { evidence_download_url_create } from "./tools/evidence_download_url_create.js";
import { evidence_upload_url_create } from "./tools/evidence_upload_url_create.js";
import { evidence_temp_file_upload_url_create } from "./tools/evidence_temp_file_upload_url_create.js";
import { evidence_multipart_upload_start } from "./tools/evidence_multipart_upload_start.js";
import { evidence_group_delete_bulk } from "./tools/evidence_group_delete_bulk.js";
import { evidence_group_create } from "./tools/evidence_group_create.js";
import { evidence_group_get } from "./tools/evidence_group_get.js";
import { evidence_group_discard } from "./tools/evidence_group_discard.js";
import { evidence_group_update } from "./tools/evidence_group_update.js";
import { evidence_group_close } from "./tools/evidence_group_close.js";
import { evidence_group_search } from "./tools/evidence_group_search.js";
import { evidence_group_update_bulk } from "./tools/evidence_group_update_bulk.js";
import { evidence_report_pdf_url_get } from "./tools/evidence_report_pdf_url_get.js";
import { evidence_report_zip_url_get } from "./tools/evidence_report_zip_url_get.js";
import { create_signature_request } from "./tools/create_signature_request.js";
import { add_document_to_signature_request } from "./tools/add_document_to_signature_request.js";
import { add_signatory_to_document } from "./tools/add_signatory_to_document.js";
import { add_validator_to_signatory } from "./tools/add_validator_to_signatory.js";
import { add_observer_to_document } from "./tools/add_observer_to_document.js";
import { activate_signature_request } from "./tools/activate_signature_request.js";
import { get_signature_request } from "./tools/get_signature_request.js";
import { signature_request_list } from "./tools/signature_request_list.js";
import { signature_request_cancel } from "./tools/signature_request_cancel.js";
import { signature_certificate_generate } from "./tools/signature_certificate_generate.js";
import { signature_coordinate_set } from "./tools/signature_coordinate_set.js";
import { signature_document_download_url_get } from "./tools/signature_document_download_url_get.js";
import { notification_request_create } from "./tools/notification_request_create.js";
import { notification_request_send } from "./tools/notification_request_send.js";
import { notification_request_status } from "./tools/notification_request_status.js";
import { notification_receiver_add } from "./tools/notification_receiver_add.js";
import { notification_document_add } from "./tools/notification_document_add.js";
import { notification_document_upload_url_create } from "./tools/notification_document_upload_url_create.js";
import { notification_document_download_url_create } from "./tools/notification_document_download_url_create.js";
import { notification_certificate_generate } from "./tools/notification_certificate_generate.js";
import { notification_certificate_pdf_url_get } from "./tools/notification_certificate_pdf_url_get.js";
import { evidence_create_sealed } from "./tools/evidence_create_sealed.js";
import { signature_request_full } from "./tools/signature_request_full.js";
import { ead_factory_help } from "./tools/ead_factory_help.js";

await createServer({
  name: "io.github.g-digital-by-Garrigues/ead-factory",
  version: "1.0.0",
  tools: [
    evidence_case_file_delete_bulk,
evidence_case_file_search,
evidence_case_file_create,
evidence_case_file_update_bulk,
evidence_case_file_get,
evidence_case_file_update,
evidence_case_file_relationship_assign,
evidence_case_file_report_preview,
evidence_case_file_report_generate,
evidence_case_file_report_update,
evidence_case_file_report_pdf_url_get,
evidence_case_file_report_zip_url_get,
evidence_case_file_status_update,
evidence_report_delete,
evidence_group_evidence_register,
evidence_group_evidence_get,
evidence_group_evidence_delete,
evidence_group_evidence_download_url_create,
evidence_group_evidence_upload_url_create,
evidence_thumbnail_url_get,
evidence_search,
generate_evidence,
evidence_update_bulk,
get_evidence,
evidence_delete,
evidence_update,
evidence_download_url_create,
evidence_upload_url_create,
evidence_temp_file_upload_url_create,
evidence_multipart_upload_start,
evidence_group_delete_bulk,
evidence_group_create,
evidence_group_get,
evidence_group_discard,
evidence_group_update,
evidence_group_close,
evidence_group_search,
evidence_group_update_bulk,
evidence_report_pdf_url_get,
evidence_report_zip_url_get,
create_signature_request,
add_document_to_signature_request,
add_signatory_to_document,
add_validator_to_signatory,
add_observer_to_document,
activate_signature_request,
get_signature_request,
signature_request_list,
signature_request_cancel,
signature_certificate_generate,
signature_coordinate_set,
signature_document_download_url_get,
notification_request_create,
notification_request_send,
notification_request_status,
notification_receiver_add,
notification_document_add,
notification_document_upload_url_create,
notification_document_download_url_create,
notification_certificate_generate,
notification_certificate_pdf_url_get,
evidence_create_sealed,
signature_request_full,
ead_factory_help,
  ],
});
