// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-ead-factory (1.0.14)
// Architecture: REST-direct (Epic 12 ADR 0008) — pure fetch(), no MCP subprocess.
// Operations: generate_evidence, get_evidence, create_signature_request, add_document_to_signature_request, add_signatory_to_document, add_observer_to_document, add_validator_to_signatory, activate_signature_request, get_signature_request

import { randomUUID } from 'node:crypto';
import {
  IDataObject,
  IExecuteFunctions,
  INodeExecutionData,
  INodeType,
  INodeTypeDescription,
  NodeOperationError,
} from 'n8n-workflow';

export class EadFactory implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'EAD Factory',
    name: 'eadFactory',
    group: ['transform'],
    version: 1,
    icon: 'file:icon.png',
    usableAsTool: true,
    codex: { categories: ['AI', 'Langchain'] },
    description: "Connect to EAD Factory to generate certified digital evidence and manage qualified signature request workflows.",
    defaults: { name: 'EAD Factory' },
    inputs: ['main'],
    outputs: ['main'],
    credentials: [{ name: 'eadFactoryApi', required: true }],
    properties: [
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        options: [
          {
            name: "Generate Evidence",
            value: 'generate_evidence',
            description: "Hashes a local file, registers it as certified evidence, uploads it to S3, and returns the completed evidence details.",
            action: "Generate Evidence",
          },
          {
            name: "Get Evidence",
            value: 'get_evidence',
            description: "Retrieves full details of an evidence record by its ID, including status, timestamps, and custody information.",
            action: "Get Evidence",
          },
          {
            name: "Create Signature Request",
            value: 'create_signature_request',
            description: "Creates a new signature request, optionally running the full flow to add participants and activate it automatically.",
            action: "Create Signature Request",
          },
          {
            name: "Add Document",
            value: 'add_document_to_signature_request',
            description: "Attaches a document to an existing signature request and uploads the file content via a secure presigned URL.",
            action: "Add Document",
          },
          {
            name: "Add Signatory",
            value: 'add_signatory_to_document',
            description: "Adds a signatory to a document inside a draft signature request and returns the new signatory ID.",
            action: "Add Signatory",
          },
          {
            name: "Add Observer",
            value: 'add_observer_to_document',
            description: "Adds an observer to a document inside a draft signature request and returns the new observer ID.",
            action: "Add Observer",
          },
          {
            name: "Add Validator",
            value: 'add_validator_to_signatory',
            description: "Assigns a validator to a signatory within a document and returns the created validator details.",
            action: "Add Validator",
          },
          {
            name: "Activate Signature Request",
            value: 'activate_signature_request',
            description: "Moves a signature request from draft to active, triggering notification emails to all signatories.",
            action: "Activate Signature Request",
          },
          {
            name: "Get Signature Request",
            value: 'get_signature_request',
            description: "Retrieves full details of a signature request by ID, including status, documents, and all participants.",
            action: "Get Signature Request",
          },
        ],
        default: 'generate_evidence',
      },
      {
        displayName: "FilePath",
        name: 'filePath',
        type: 'string',
        default: "",
        description: "Absolute path to the file on disk (e.g. /home/user/contract.pdf)",
        required: true,
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "EvidenceId",
        name: 'evidenceId',
        type: 'string',
        default: "",
        description: "Unique UUID for this evidence (used for idempotency)",
        required: true,
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "Title",
        name: 'title',
        type: 'string',
        default: "",
        description: "Human-readable title for the evidence",
        required: true,
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "CreatedBy",
        name: 'createdBy',
        type: 'string',
        default: "",
        description: "Name of the person creating the evidence (max 50 characters)",
        required: true,
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "CapturedAt",
        name: 'capturedAt',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime when the evidence was captured (e.g. 2024-11-01T10:00:00Z)",
        required: true,
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "CustodyType",
        name: 'custodyType',
        type: 'options',
        options: [
          { name: "INTERNAL", value: "INTERNAL" },
          { name: "EXTERNAL", value: "EXTERNAL" },
        ],
        default: "INTERNAL",
        description: "INTERNAL = file hosted by the platform, EXTERNAL = hosted externally. Defaults to INTERNAL.",
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "TestimonyTSP",
        name: 'testimonyTSP',
        type: 'boolean',
        default: false,
        description: "Enable TSP timestamping via EADTrust (qualified eIDAS). Defaults to true if no testimony specified.",
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "TestimonyDLT",
        name: 'testimonyDLT',
        type: 'boolean',
        default: false,
        description: "Enable DLT timestamping via Lacnet blockchain. Requires prior tenant activation.",
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "RequiredTestimonyProviders",
        name: 'requiredTestimonyProviders',
        type: 'string',
        default: "",
        description: "Comma-separated required providers: \"TSP\", \"DLT\", or \"TSP,DLT\". Omit to use tenant defaults.",
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "Metadata",
        name: 'metadata',
        type: 'string',
        default: "",
        description: "JSON string of key-value pairs for custom business data (e.g. {\"contractRef\":\"CTR-2024-001\"}).",
        displayOptions: { show: { operation: ['generate_evidence'] } },
      },
      {
        displayName: "EvidenceId",
        name: 'evidenceId',
        type: 'string',
        default: "",
        description: "UUID of the evidence to retrieve",
        required: true,
        displayOptions: { show: { operation: ['get_evidence'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        description: "Name of the signature request",
        required: true,
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "CreatedBy",
        name: 'createdBy',
        type: 'string',
        default: "",
        description: "Identifier of the user creating the request (e.g. email or username)",
        required: true,
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "Item Description",
        name: 'description',
        type: 'string',
        default: "",
        description: "Short plain-text description (e.g. \"My case file\"). Required by the API.",
        required: true,
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "Notifications",
        name: 'notifications',
        type: 'boolean',
        default: false,
        description: "Whether to send email notifications to participants. Defaults to tenant configuration.",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'string',
        default: "es_ES",
        description: "Language code for notifications and UI (e.g. \"ES\", \"EN\")",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "UniqueValidator",
        name: 'uniqueValidator',
        type: 'boolean',
        default: false,
        description: "Whether a single validator can validate all signatories",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "Provider",
        name: 'provider',
        type: 'options',
        options: [
          { name: "NOTICEMAN", value: "NOTICEMAN" },
          { name: "NOTICEMAN_AND_WHATSAPP", value: "NOTICEMAN_AND_WHATSAPP" },
        ],
        default: "NOTICEMAN",
        description: "Notification provider. NOTICEMAN = email only, NOTICEMAN_AND_WHATSAPP = email + WhatsApp",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "SenderName",
        name: 'senderName',
        type: 'string',
        default: "",
        description: "Display name of the sender shown to participants",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "SenderAddress",
        name: 'senderAddress',
        type: 'string',
        default: "",
        description: "Reply-to email address for notifications",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "CloseCondition",
        name: 'closeCondition',
        type: 'options',
        options: [
          { name: "ALL_REQUIRED", value: "ALL_REQUIRED" },
          { name: "PARTIAL_ALLOWED", value: "PARTIAL_ALLOWED" },
        ],
        default: "ALL_REQUIRED",
        description: "Condition to close the request: ALL_REQUIRED = all signatories must sign, PARTIAL_ALLOWED = partial signatures accepted",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "CloseAt",
        name: 'closeAt',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime after which the request is automatically closed (e.g. 2025-12-31T23:59:59Z)",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "SignatureRequestBody",
        name: 'signatureRequestBody',
        type: 'string',
        default: "",
        description: "JSON array of body objects to customise notification emails. Each item: { \"status\": \"DRAFT\"|\"ACTIVE\"|..., \"content\": { \"subject\": \"...\", \"body\": \"...\", \"additionalText\": \"...\" } }",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "FullFlow",
        name: 'fullFlow',
        type: 'boolean',
        default: false,
        description: "When true, after creating the SR automatically: (1) adds /Users/valonso/00-Proyectos/02-MCP Market Distribution/pipeline-repo/MCP_Market_Distribution/pending-to-publish/ead-factory as a document, (2) adds a signatory (+signatory@undefined), (3) adds a validator (+validator@undefined) to the signatory, (4) adds an observer (+observer@undefined), (5) activates the SR.",
        displayOptions: { show: { operation: ['create_signature_request'] } },
      },
      {
        displayName: "SignatureRequestId",
        name: 'signatureRequestId',
        type: 'string',
        default: "",
        description: "UUID of the signature request to add the document to",
        required: true,
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "FilePath",
        name: 'filePath',
        type: 'string',
        default: "",
        description: "Absolute path to the file on disk (e.g. /home/user/contract.pdf)",
        required: true,
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "Title",
        name: 'title',
        type: 'string',
        default: "",
        description: "Human-readable title for the document",
        required: true,
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "SignatureType",
        name: 'signatureType',
        type: 'options',
        options: [
          { name: "INTERPOSITION", value: "INTERPOSITION" },
          { name: "ADVANCED", value: "ADVANCED" },
          { name: "OTHER", value: "OTHER" },
        ],
        default: "INTERPOSITION",
        description: "Type of signature: INTERPOSITION, ADVANCED, or OTHER",
        required: true,
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "Item Description",
        name: 'description',
        type: 'string',
        default: "",
        description: "Short plain-text description (e.g. \"My case file\"). Required by the API.",
        required: true,
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "SignatureDeadline",
        name: 'signatureDeadline',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime deadline for signing this document (e.g. 2025-12-31T23:59:59Z)",
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "Provider",
        name: 'provider',
        type: 'options',
        options: [
          { name: "EADTRUST", value: "EADTRUST" },
        ],
        default: "EADTRUST",
        description: "Signing provider. Currently only EADTRUST is supported.",
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "EvidenceId",
        name: 'evidenceId',
        type: 'string',
        default: "",
        description: "UUID of an existing evidence to link to this document",
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "Metadata",
        name: 'metadata',
        type: 'string',
        default: "",
        description: "JSON object of string key-value pairs for custom business data (e.g. {\"ref\":\"DOC-001\"})",
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "CertificateFilesOriginalDocument",
        name: 'certificateFilesOriginalDocument',
        type: 'boolean',
        default: false,
        description: "Include the original document in the certificate package",
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "CertificateFilesSignedDocument",
        name: 'certificateFilesSignedDocument',
        type: 'boolean',
        default: false,
        description: "Include the signed document in the certificate package",
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "Sequence",
        name: 'sequence',
        type: 'number',
        default: 0,
        description: "Order/sequence number of the document within the request",
        typeOptions: {"numberPrecision":0},
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "FileSize",
        name: 'fileSize',
        type: 'number',
        default: 0,
        description: "Size of the file in bytes",
        typeOptions: {"minValue":1,"numberPrecision":0},
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "Detached",
        name: 'detached',
        type: 'boolean',
        default: false,
        description: "Whether the signature is detached from the document",
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "ConvertToPdf",
        name: 'convertToPdf',
        type: 'boolean',
        default: false,
        description: "Whether to convert the document to PDF before signing",
        displayOptions: { show: { operation: ['add_document_to_signature_request'] } },
      },
      {
        displayName: "SignatureRequestId",
        name: 'signatureRequestId',
        type: 'string',
        default: "",
        description: "UUID of the signature request",
        required: true,
        displayOptions: { show: { operation: ['add_signatory_to_document'] } },
      },
      {
        displayName: "DocumentId",
        name: 'documentId',
        type: 'string',
        default: "",
        description: "UUID of the document to add the signatory to",
        required: true,
        displayOptions: { show: { operation: ['add_signatory_to_document'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        description: "First name of the signatory",
        required: true,
        displayOptions: { show: { operation: ['add_signatory_to_document'] } },
      },
      {
        displayName: "Email",
        name: 'email',
        type: 'string',
        default: "",
        description: "Email address of the signatory",
        required: true,
        displayOptions: { show: { operation: ['add_signatory_to_document'] } },
      },
      {
        displayName: "Surnames",
        name: 'surnames',
        type: 'string',
        default: "",
        description: "Surnames of the signatory",
        displayOptions: { show: { operation: ['add_signatory_to_document'] } },
      },
      {
        displayName: "Phone",
        name: 'phone',
        type: 'string',
        default: "",
        description: "Phone number of the signatory (used for WhatsApp notifications)",
        displayOptions: { show: { operation: ['add_signatory_to_document'] } },
      },
      {
        displayName: "Sequence",
        name: 'sequence',
        type: 'number',
        default: 0,
        description: "Signing order sequence number",
        typeOptions: {"numberPrecision":0},
        displayOptions: { show: { operation: ['add_signatory_to_document'] } },
      },
      {
        displayName: "UniqueValidator",
        name: 'uniqueValidator',
        type: 'boolean',
        default: false,
        description: "Whether this signatory has a unique validator assigned",
        displayOptions: { show: { operation: ['add_signatory_to_document'] } },
      },
      {
        displayName: "Coordinates",
        name: 'coordinates',
        type: 'string',
        default: "",
        description: "JSON array of signature position coordinates. Each item: { \"x\": number, \"y\": number, \"page\": number }",
        displayOptions: { show: { operation: ['add_signatory_to_document'] } },
      },
      {
        displayName: "SignatureRequestId",
        name: 'signatureRequestId',
        type: 'string',
        default: "",
        description: "UUID of the signature request",
        required: true,
        displayOptions: { show: { operation: ['add_observer_to_document'] } },
      },
      {
        displayName: "DocumentId",
        name: 'documentId',
        type: 'string',
        default: "",
        description: "UUID of the document to add the observer to",
        required: true,
        displayOptions: { show: { operation: ['add_observer_to_document'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        description: "First name of the observer",
        required: true,
        displayOptions: { show: { operation: ['add_observer_to_document'] } },
      },
      {
        displayName: "Email",
        name: 'email',
        type: 'string',
        default: "",
        description: "Email address of the observer",
        required: true,
        displayOptions: { show: { operation: ['add_observer_to_document'] } },
      },
      {
        displayName: "Surnames",
        name: 'surnames',
        type: 'string',
        default: "",
        description: "Surnames of the observer",
        displayOptions: { show: { operation: ['add_observer_to_document'] } },
      },
      {
        displayName: "DocumentId",
        name: 'documentId',
        type: 'string',
        default: "",
        description: "UUID of the document",
        required: true,
        displayOptions: { show: { operation: ['add_validator_to_signatory'] } },
      },
      {
        displayName: "SignatoryId",
        name: 'signatoryId',
        type: 'string',
        default: "",
        description: "UUID of the signatory to add the validator to",
        required: true,
        displayOptions: { show: { operation: ['add_validator_to_signatory'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        description: "First name of the validator",
        required: true,
        displayOptions: { show: { operation: ['add_validator_to_signatory'] } },
      },
      {
        displayName: "Email",
        name: 'email',
        type: 'string',
        default: "",
        description: "Email address of the validator",
        required: true,
        displayOptions: { show: { operation: ['add_validator_to_signatory'] } },
      },
      {
        displayName: "Surnames",
        name: 'surnames',
        type: 'string',
        default: "",
        description: "Surnames of the validator",
        displayOptions: { show: { operation: ['add_validator_to_signatory'] } },
      },
      {
        displayName: "Phone",
        name: 'phone',
        type: 'string',
        default: "",
        description: "Phone number of the validator",
        displayOptions: { show: { operation: ['add_validator_to_signatory'] } },
      },
      {
        displayName: "SignatureRequestId",
        name: 'signatureRequestId',
        type: 'string',
        default: "",
        description: "UUID of the signature request to activate",
        required: true,
        displayOptions: { show: { operation: ['activate_signature_request'] } },
      },
      {
        displayName: "SignatureRequestId",
        name: 'signatureRequestId',
        type: 'string',
        default: "",
        description: "UUID of the signature request to retrieve",
        required: true,
        displayOptions: { show: { operation: ['get_signature_request'] } },
      },
    ],
  };

  async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
    const items = this.getInputData();
    const out: INodeExecutionData[] = [];
    const creds = await this.getCredentials('eadFactoryApi');
    const baseUrl = String(creds.baseUrl ?? '').replace(/\/$/, '');

    // --- Obtain Bearer token (once per execute call) ---
    const tokenParams = new URLSearchParams({
      grant_type: 'client_credentials',
      client_id: String(creds.OKTA_CLIENT_ID ?? ''),
      client_secret: String(creds.OKTA_CLIENT_SECRET ?? ''),
      scope: String(creds.OKTA_SCOPE ?? 'token'),
    });
    const tokenRes = await fetch(String(creds.OKTA_TOKEN_URL ?? ''), {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: tokenParams.toString(),
    });
    if (!tokenRes.ok) {
      throw new NodeOperationError(this.getNode(), `Auth failed: HTTP ${tokenRes.status}. Check OKTA_TOKEN_URL, OKTA_CLIENT_ID, and OKTA_CLIENT_SECRET.`);
    }
    const tokenBody = await tokenRes.json() as { access_token?: string };
    const bearer = tokenBody.access_token ?? '';

    // --- Per-item REST calls ---
    for (let i = 0; i < items.length; i++) {
      try {
        const operation = this.getNodeParameter('operation', i) as string;
        const meta = OPERATION_META[operation];
        if (!meta) {
          throw new NodeOperationError(this.getNode(), `Unknown operation: ${operation}`, { itemIndex: i });
        }
        if (meta.stub) {
          throw new NodeOperationError(
            this.getNode(),
            `Operation '${operation}' requires n8n self-hosted with the @g-digital/mcp-* package. It is not available in n8n Cloud via this connector.`,
            { itemIndex: i },
          );
        }

        // Replace URL path params {paramName} from input; remaining args → body/query
        let url = `${baseUrl}${meta.urlTemplate}`;
        const propsForOp = OPERATION_PROPERTY_NAMES[operation] ?? [];
        const body: IDataObject = {};
        const isCreateOrAdd = operation.endsWith('_create') || operation.endsWith('_add');
        let generatedId: string | undefined;
        for (const propName of propsForOp) {
          let val = this.getNodeParameter(propName, i);
          // Auto-generate UUID for 'id' in _create/_add BEFORE the skip check
          if (propName === 'id' && isCreateOrAdd && (val === '' || val === null || val === undefined)) {
            val = randomUUID();
            generatedId = val as string;
          }
          if (val === '' || val === null || val === undefined) continue;
          if (typeof val === 'object' && !Array.isArray(val) && Object.keys(val as object).length === 0) continue;
          const placeholder = `{${propName}}`;
          if (url.includes(placeholder)) {
            url = url.replace(placeholder, encodeURIComponent(String(val)));
          } else {
            body[propName] = val;
          }
        }
        // Substitute any remaining {placeholder} patterns from credentials.
        // First try exact credential key names, then common API→credential aliases
        // (e.g. {email} in session_info maps to credential field MCP_AUTH_EMAIL).
        const credAliases: Record<string, string> = { email: 'MCP_AUTH_EMAIL' };
        for (const [credKey, credVal] of Object.entries(creds)) {
          const placeholder = `{${credKey}}`;
          if (url.includes(placeholder) && credVal) {
            url = url.replace(placeholder, encodeURIComponent(String(credVal)));
          }
        }
        for (const [alias, credKey] of Object.entries(credAliases)) {
          const placeholder = `{${alias}}`;
          if (url.includes(placeholder) && creds[credKey]) {
            url = url.replace(placeholder, encodeURIComponent(String(creds[credKey])));
          }
        }

        // --- Smart defaults for remaining body fields ---
        // validityFrom: default to now (ISO 8601)
        if ('validityFrom' in body && (body.validityFrom === '' || body.validityFrom === null || body.validityFrom === undefined)) {
          body.validityFrom = new Date().toISOString();
        }
        // validityTo: default to 1 year from now
        if ('validityTo' in body && (body.validityTo === '' || body.validityTo === null || body.validityTo === undefined)) {
          const oneYearLater = new Date();
          oneYearLater.setFullYear(oneYearLater.getFullYear() + 1);
          body.validityTo = oneYearLater.toISOString();
        }

        const isBodyless = meta.method === 'GET' || meta.method === 'DELETE';
        if (isBodyless && Object.keys(body).length > 0) {
          // hey-api client uses bracket notation for nested object query params,
          // matching the qs library used by NestJS on the server:
          // { filter: { ownerId: 'uuid' }, page: { number: 1, size: 20 } }
          //   → filter[ownerId]=uuid&page[number]=1&page[size]=20
          const flattenQs = (obj: IDataObject, prefix = ''): Array<[string, string]> => {
            const pairs: Array<[string, string]> = [];
            for (const [k, v] of Object.entries(obj)) {
              if (v === null || v === undefined || v === '') continue;
              const key = prefix ? `${prefix}[${k}]` : k;
              if (typeof v === 'object' && !Array.isArray(v)) {
                if (Object.keys(v as object).length === 0) continue;
                pairs.push(...flattenQs(v as IDataObject, key));
              } else if (Array.isArray(v)) {
                for (const item of v) pairs.push([`${key}[]`, String(item)]);
              } else {
                pairs.push([key, String(v)]);
              }
            }
            return pairs;
          };
          const pairs = flattenQs(body);
          if (pairs.length > 0) {
            url = `${url}?${new URLSearchParams(pairs).toString()}`;
          }
        }

        const apiRes = await fetch(url, {
          method: meta.method,
          headers: {
            Authorization: `Bearer ${bearer}`,
            ...(isBodyless ? {} : { 'Content-Type': 'application/json' }),
          },
          ...(isBodyless ? {} : { body: JSON.stringify(body) }),
        });

        if (!apiRes.ok) {
          const errText = await apiRes.text().catch(() => '');
          throw new NodeOperationError(
            this.getNode(),
            `${operation} failed: HTTP ${apiRes.status}${errText ? ` — ${errText.slice(0, 200)}` : ''}`,
            { itemIndex: i },
          );
        }

        // 204 No Content or empty body → return empty object
        const contentLength = apiRes.headers.get('content-length');
        const hasBody = apiRes.status !== 204 && contentLength !== '0';
        const json: IDataObject = hasBody
          ? await apiRes.json().catch(() => ({})) as IDataObject
          : {};
        // Inject auto-generated id with semantic field name so downstream nodes
        // can reference it directly (e.g. $json.caseFileId, $json.chatId).
        if (generatedId) {
          const semanticId = AUTO_ID_OUTPUT_FIELD[operation];
          if (semanticId && !json[semanticId]) json[semanticId] = generatedId;
          if (!json['id']) json['id'] = generatedId;
        }
        // chat_certificate_get: when CERTIFIED, fetch documentUrl via a second call
        if (operation === 'chat_certificate_get' && (json as IDataObject).status === 'CERTIFIED' && !json['documentUrl']) {
          try {
            const docUrlRes = await fetch(`${url}/document-url`, {
              headers: { Authorization: `Bearer ${bearer}` },
            });
            if (docUrlRes.ok) {
              const docData = await docUrlRes.json().catch(() => ({})) as IDataObject;
              if (docData.documentUrl) (json as IDataObject).documentUrl = docData.documentUrl;
            }
          } catch { /* non-fatal */ }
        }
        // session_info: inject userId decoded from JWT sub claim so callers
        // don't need a separate step to obtain the userId required by most operations.
        if (operation === 'session_info' && bearer) {
          try {
            const parts = bearer.split('.');
            if (parts.length === 3) {
              const pad = (s: string) => s + '='.repeat((4 - s.length % 4) % 4);
              const payload = JSON.parse(Buffer.from(pad(parts[1] ?? ''), 'base64').toString('utf8')) as IDataObject;
              const sub = payload.sub ?? payload.userId ?? payload.user_id;
              if (sub && !(json as IDataObject).userId) {
                (json as IDataObject).userId = sub;
              }
            }
          } catch { /* ignore decode errors */ }
        }
        out.push({ json: json as IDataObject });
      } catch (error) {
        if (this.continueOnFail()) {
          out.push({ json: this.getInputData(i)[0].json, error: error as NodeOperationError });
          continue;
        }
        throw error;
      }
    }

    return [out];
  }
}

// Semantic output field name for auto-generated 'id' values.
// When a _create/_add operation auto-generates a UUID for 'id', it is also
// injected into the output under this field name so downstream nodes can
// reference it with its domain-specific name (e.g. $json.caseFileId).
const AUTO_ID_OUTPUT_FIELD: Record<string, string> = {
  case_file_create: 'caseFileId',
  evidence_create: 'evidenceId',
  evidence_group_create: 'evidenceGroupId',
  dossier_create: 'dossierId',
  dossier_group_certify: 'dossierId',
  notification_request_create: 'notificationRequestId',
  notification_receiver_add: 'receiverId',
  notification_document_add: 'documentId',
  chat_create: 'chatId',
  chat_certificate_create: 'certificateId',
  signature_request_create: 'requestId',
  signature_group_create: 'groupId',
  signature_participant_create: 'signatoryId',
};

// HTTP metadata per operation — method + URL template.
// 'stub: true' means the tool has no REST annotation and requires self-hosted n8n.
const OPERATION_META: Record<string, { method: string; urlTemplate: string; stub?: true }> = {
  'generate_evidence': { method: 'STUB', urlTemplate: "", stub: true },
  'get_evidence': { method: 'STUB', urlTemplate: "", stub: true },
  'create_signature_request': { method: 'STUB', urlTemplate: "", stub: true },
  'add_document_to_signature_request': { method: 'STUB', urlTemplate: "", stub: true },
  'add_signatory_to_document': { method: 'STUB', urlTemplate: "", stub: true },
  'add_observer_to_document': { method: 'STUB', urlTemplate: "", stub: true },
  'add_validator_to_signatory': { method: 'STUB', urlTemplate: "", stub: true },
  'activate_signature_request': { method: 'STUB', urlTemplate: "", stub: true },
  'get_signature_request': { method: 'STUB', urlTemplate: "", stub: true },
};

// Per-operation input property names for argument gathering.
const OPERATION_PROPERTY_NAMES: Record<string, readonly string[]> = {
  'generate_evidence': ['filePath', 'evidenceId', 'title', 'createdBy', 'capturedAt', 'custodyType', 'testimonyTSP', 'testimonyDLT', 'requiredTestimonyProviders', 'metadata'],
  'get_evidence': ['evidenceId'],
  'create_signature_request': ['name', 'createdBy', 'description', 'notifications', 'language', 'uniqueValidator', 'provider', 'senderName', 'senderAddress', 'closeCondition', 'closeAt', 'signatureRequestBody', 'fullFlow'],
  'add_document_to_signature_request': ['signatureRequestId', 'filePath', 'title', 'signatureType', 'description', 'signatureDeadline', 'provider', 'evidenceId', 'metadata', 'certificateFilesOriginalDocument', 'certificateFilesSignedDocument', 'sequence', 'fileSize', 'detached', 'convertToPdf'],
  'add_signatory_to_document': ['signatureRequestId', 'documentId', 'name', 'email', 'surnames', 'phone', 'sequence', 'uniqueValidator', 'coordinates'],
  'add_observer_to_document': ['signatureRequestId', 'documentId', 'name', 'email', 'surnames'],
  'add_validator_to_signatory': ['documentId', 'signatoryId', 'name', 'email', 'surnames', 'phone'],
  'activate_signature_request': ['signatureRequestId'],
  'get_signature_request': ['signatureRequestId'],
 };
