// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: Signature_activate (POST /api/v1/private/signature-requests/{signatureRequestId}/activate)

import { defineTool, applyFieldGlosses } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { signatureActivate } from "../api/sdk.gen.js";
import { zSignatureActivatePath } from "../api/zod.gen.js";
import { zSignatureActivateResponse } from "../api/zod.gen.js";
const rawInputSchema = z.object({
  ...zSignatureActivatePath.shape,
});
// Story 6.5 (FR-27/P-A5): fills in descriptions for commonly reused field names
// (e.g. caseFileId) that Hey API's generated schema doesn't carry on its own.
const inputSchema = applyFieldGlosses(rawInputSchema, {"caseFileId":"MANDATORY. UUID of the parent case file. Obtain from evidence_case_file_create.","evidenceGroupId":"MANDATORY. UUID of the evidence group. Obtain from evidence_group_create.","evidenceId":"MANDATORY. UUID of the evidence record. Obtain from evidence_group_evidence_register or generate_evidence.","reportId":"MANDATORY. UUID of the report.","signatureRequestId":"MANDATORY. UUID of the signature request. Obtain from create_signature_request.","documentId":"MANDATORY. UUID of the document within the signature request. Obtain from add_document_to_signature_request.","signatoryId":"MANDATORY. UUID of the signatory. Obtain from add_signatory_to_document.","validatorId":"MANDATORY. UUID of the validator. Obtain from add_validator_to_signatory.","observerId":"MANDATORY. UUID of the observer. Obtain from add_observer_to_document.","requestId":"UUID of the notification request. Obtain from notification_request_create.","attachmentId":"MANDATORY. UUID of the attachment. Obtain from notification_document_add."});

export const activate_signature_request = defineTool({
  name: "activate_signature_request",
  description: "Activates a signature request, sending signing notifications to every added signatory — after this, no more documents or signatories can be added (use add_validator_to_signatory / add_observer_to_document before activating if you need those roles). Requires: create_signature_request → signatureRequestId, at least one document (add_document_to_signature_request) with its bytes uploaded, and at least one signatory per document (add_signatory_to_document). Prefer signature_request_full for a new request — it creates, adds documents+signatories, and activates in one call.",
  inputSchema,
  outputSchema: zSignatureActivateResponse,
  annotations: {
    title: "Activate Signature Request",
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL_SIGNATURE ?? process.env.MCP_API_BASE_URL ?? "https://api.gcloudfactory.com/signature-manager",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = signatureActivate as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zSignatureActivatePath.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    // Story 6.6 (FR-30/§5.4): tells the agent what to call next without a separate lookup.
    return { ...response.data, nextSteps: [{"suggestedTool":"get_signature_request","why":"Check signing progress after activation."}] };
  },
});
