// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: Signature_createSignatureRequest (POST /api/v1/private/signature-requests)

import { defineTool, applyFieldGlosses } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { signatureCreateSignatureRequest } from "../api/sdk.gen.js";
import { zSignatureCreateSignatureRequestBody } from "../api/zod.gen.js";
import { zSignatureCreateSignatureRequestResponse } from "../api/zod.gen.js";
const rawInputSchema = z.object({
  ...zSignatureCreateSignatureRequestBody.shape,
});
// Story 6.5 (FR-27/P-A5): fills in descriptions for commonly reused field names
// (e.g. caseFileId) that Hey API's generated schema doesn't carry on its own.
const inputSchema = applyFieldGlosses(rawInputSchema, {"caseFileId":"MANDATORY. UUID of the parent case file. Obtain from evidence_case_file_create.","evidenceGroupId":"MANDATORY. UUID of the evidence group. Obtain from evidence_group_create.","evidenceId":"MANDATORY. UUID of the evidence record. Obtain from evidence_group_evidence_register or generate_evidence.","reportId":"MANDATORY. UUID of the report.","signatureRequestId":"MANDATORY. UUID of the signature request. Obtain from create_signature_request.","documentId":"MANDATORY. UUID of the document within the signature request. Obtain from add_document_to_signature_request.","signatoryId":"MANDATORY. UUID of the signatory. Obtain from add_signatory_to_document.","validatorId":"MANDATORY. UUID of the validator. Obtain from add_validator_to_signatory.","observerId":"MANDATORY. UUID of the observer. Obtain from add_observer_to_document.","requestId":"UUID of the notification request. Obtain from notification_request_create.","attachmentId":"MANDATORY. UUID of the attachment. Obtain from notification_document_add."});

export const create_signature_request = defineTool({
  name: "create_signature_request",
  description: "Creates a new signature request — the top-level container for documents and signatories in a signing flow. Use this first, before add_document_to_signature_request. No prerequisites. Example: create_signature_request({ name: 'NDA — Acme Corp', createdBy: 'jane@company.com' }) returns { id, ... } — use the returned id as signatureRequestId in subsequent calls.",
  inputSchema,
  outputSchema: zSignatureCreateSignatureRequestResponse,
  annotations: {
    title: "Create Signature Request",
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api.gcloudfactory.com",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = signatureCreateSignatureRequest as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      body: zSignatureCreateSignatureRequestBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    // Story 6.6 (FR-30/§5.4): tells the agent what to call next without a separate lookup.
    return { ...response.data, nextSteps: [{"suggestedTool":"add_document_to_signature_request","why":"Add at least one document before adding signatories or activating."}] };
  },
});
