// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: Evidence_createEvidenceGroup (POST /api/v1/private/case-files/{caseFileId}/evidence-groups)

import { defineTool, applyFieldGlosses } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { evidenceCreateEvidenceGroup } from "../api/sdk.gen.js";
import { zEvidenceCreateEvidenceGroupPath } from "../api/zod.gen.js";
import { zEvidenceCreateEvidenceGroupBody } from "../api/zod.gen.js";
import { zEvidenceCreateEvidenceGroupResponse } from "../api/zod.gen.js";
const rawInputSchema = z.object({
  ...zEvidenceCreateEvidenceGroupPath.shape,
  ...zEvidenceCreateEvidenceGroupBody.shape,
});
// Story 6.5 (FR-27/P-A5): fills in descriptions for commonly reused field names
// (e.g. caseFileId) that Hey API's generated schema doesn't carry on its own.
const inputSchema = applyFieldGlosses(rawInputSchema, {"caseFileId":"MANDATORY. UUID of the parent case file. Obtain from evidence_case_file_create.","evidenceGroupId":"MANDATORY. UUID of the evidence group. Obtain from evidence_group_create.","evidenceId":"MANDATORY. UUID of the evidence record. Obtain from evidence_group_evidence_register or generate_evidence.","reportId":"MANDATORY. UUID of the report.","signatureRequestId":"MANDATORY. UUID of the signature request. Obtain from create_signature_request.","documentId":"MANDATORY. UUID of the document within the signature request. Obtain from add_document_to_signature_request.","signatoryId":"MANDATORY. UUID of the signatory. Obtain from add_signatory_to_document.","validatorId":"MANDATORY. UUID of the validator. Obtain from add_validator_to_signatory.","observerId":"MANDATORY. UUID of the observer. Obtain from add_observer_to_document.","requestId":"UUID of the notification request. Obtain from notification_request_create.","attachmentId":"MANDATORY. UUID of the attachment. Obtain from notification_document_add."});

export const evidence_group_create = defineTool({
  name: "evidence_group_create",
  description: "Creates an evidence group inside a case file — evidence records are always registered inside a group, never standalone (except via the legacy generate_evidence tool). Use when starting a new batch of related evidence (e.g. all files for one incident). Requires: evidence_case_file_create → caseFileId. Example: evidence_group_create({ caseFileId, type: 'FILE' }) returns { id, status: 'OPEN' } — use the returned id as evidenceGroupId in evidence_group_evidence_register, then evidence_group_close once every evidence in the group has been uploaded.",
  inputSchema,
  outputSchema: zEvidenceCreateEvidenceGroupResponse,
  annotations: {
    title: "Evidence Group Create",
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL_EVIDENCE ?? process.env.MCP_API_BASE_URL ?? "https://api.gcloudfactory.com/digital-trust",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = evidenceCreateEvidenceGroup as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zEvidenceCreateEvidenceGroupPath.parse(inp),
      body: zEvidenceCreateEvidenceGroupBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    // Story 6.6 (FR-30/§5.4): tells the agent what to call next without a separate lookup.
    return { ...response.data, nextSteps: [{"suggestedTool":"evidence_group_evidence_register","why":"Register one or more evidence files into this OPEN group."}] };
  },
});
