// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: Notification_getReportPdf (GET /api/v1/private/reports/{reportId}/file)

import { defineTool, applyFieldGlosses, NON_OBJECT_SCHEMA_WRAPPER_KEY, UpstreamHttpError } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { notificationGetReportPdf } from "../api/sdk.gen.js";
import { zNotificationGetReportPdfPath } from "../api/zod.gen.js";
import { zNotificationGetReportPdfResponse } from "../api/zod.gen.js";
const rawInputSchema = z.object({
  ...zNotificationGetReportPdfPath.shape,
});
// Story 6.5 (FR-27/P-A5): fills in descriptions for commonly reused field names
// (e.g. caseFileId) that Hey API's generated schema doesn't carry on its own.
const inputSchema = applyFieldGlosses(rawInputSchema, {"caseFileId":"MANDATORY. UUID of the parent case file. Obtain from evidence_case_file_create.","evidenceGroupId":"MANDATORY. UUID of the evidence group. Obtain from evidence_group_create.","evidenceId":"MANDATORY. UUID of the evidence record. Obtain from evidence_group_evidence_register or generate_evidence.","reportId":"MANDATORY. UUID of the report.","signatureRequestId":"MANDATORY. UUID of the signature request. Obtain from create_signature_request.","documentId":"MANDATORY. UUID of the document within the signature request. Obtain from add_document_to_signature_request.","signatoryId":"MANDATORY. UUID of the signatory. Obtain from add_signatory_to_document.","validatorId":"MANDATORY. UUID of the validator. Obtain from add_validator_to_signatory.","observerId":"MANDATORY. UUID of the observer. Obtain from add_observer_to_document.","requestId":"UUID of the notification request. Obtain from notification_request_create.","attachmentId":"MANDATORY. UUID of the attachment. Obtain from notification_document_add."});

export const notification_certificate_pdf_url_get = defineTool({
  name: "notification_certificate_pdf_url_get",
  description: "Retrieves the download URL for a previously generated notification delivery certificate. Requires: notification_certificate_generate → reportId.",
  inputSchema,
  outputSchema: zNotificationGetReportPdfResponse,
  annotations: {
    title: "Notification Certificate Pdf Url Get",
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL_NOTIFICATION ?? process.env.MCP_API_BASE_URL ?? "https://api.gcloudfactory.com/notifications",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = notificationGetReportPdf as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zNotificationGetReportPdfPath.parse(inp),
    });

    if (response.error !== undefined) {
      // Story 10.2: constructs a status-aware UpstreamHttpError instead of a plain
      // Error — mapUpstreamError's 422 field-hint / 5xx transient-retry branches can
      // only be reached this way; a plain Error always fell through to the generic
      // "transient failure" text, discarding the real HTTP status/detail. Uses
      // fromParsedError (not fromResponse) because @hey-api/client-fetch has already
      // consumed response.response's body to populate response.error by this point.
      throw UpstreamHttpError.fromParsedError(response.response?.status ?? 0, response.error, "notification_certificate_pdf_url_get");
    }
    // Story 10.1: the response schema is not a top-level ZodObject (bare
    // z.array/z.record/z.intersection) — the MCP protocol's structuredContent must be
    // object-shaped, so extractZodShape (server.ts) wraps the ADVERTISED outputSchema
    // under NON_OBJECT_SCHEMA_WRAPPER_KEY; the actual return value must match.
    return { [NON_OBJECT_SCHEMA_WRAPPER_KEY]: response.data };
  },
});
